ADA_USD_IPERP: '1'
BTCUSDH24: '1'
BTCUSDZ23: '1'
BTC_USD_IPERP: '1'
DOT_USD_IPERP: '1'
EOS_USD_IPERP: '1'
ETHUSDH24: '1'
ETHUSDZ23: '1'
ETH_USD_IPERP: '1'
LTC_USD_IPERP: '1'
MANA_USD_IPERP: '1'
XRP_USD_IPERP: '1'
