1INCH_USDT_SPOT: '0.01'
1SOL_USDT_SPOT: '0.01'
3P_USDT_SPOT: '0.1'
AAVE_USDT_SPOT: '0.001'
ACA_USDT_SPOT: '0.01'
ACH_USDT_SPOT: '0.1'
ACM_USDT_SPOT: '0.01'
ACS_USDT_SPOT: '0.01'
ADA2L_USDT_SPOT: '0.0001'
ADA2S_USDT_SPOT: '0.0001'
ADA_EUR_SPOT: '0.01'
ADA_USDC_SPOT: '0.01'
ADA_USDT_SPOT: '0.01'
AFC_USDT_SPOT: '0.01'
AGIX_USDT_SPOT: '0.01'
AGI_USDT_SPOT: '0.01'
AGLA_USDT_SPOT: '0.01'
AGLD_USDT_SPOT: '0.01'
ALGO_BTC_SPOT: '0.1'
ALGO_USDT_SPOT: '0.01'
ANKR_USDT_SPOT: '0.1'
APE2L_USDT_SPOT: '0.0001'
APE2S_USDT_SPOT: '0.0001'
APEX_USDC_SPOT: '0.01'
APEX_USDT_SPOT: '0.01'
APE_USDC_SPOT: '0.01'
APE_USDT_SPOT: '0.01'
APT_USDC_SPOT: '0.01'
APT_USDT_SPOT: '0.01'
ARB_USDC_SPOT: '0.01'
ARB_USDT_SPOT: '0.01'
ARKM_USDT_SPOT: '0.01'
AR_USDT_SPOT: '0.01'
ATOM2L_USDT_SPOT: '0.0001'
ATOM2S_USDT_SPOT: '0.0001'
ATOM_USDT_SPOT: '0.001'
AVAX2L_USDT_SPOT: '0.0001'
AVAX2S_USDT_SPOT: '0.0001'
AVAX_USDC_SPOT: '0.001'
AVAX_USDT_SPOT: '0.001'
AVA_USDT_SPOT: '0.01'
AXL_USDT_SPOT: '0.01'
AXS_USDT_SPOT: '0.01'
AZY_USDT_SPOT: '0.01'
BABYDOGE_USDT_SPOT: '0.1'
BAR_USDT_SPOT: '0.01'
BAT_USDT_SPOT: '0.01'
BCH_USDT_SPOT: '0.001'
BEAM_USDT_SPOT: '0.01'
BEL_USDT_SPOT: '0.01'
BICO_USDT_SPOT: '0.01'
BLUR_USDT_SPOT: '0.01'
BNB_USDT_SPOT: '0.00001'
BNT_USDT_SPOT: '0.01'
BOBA_USDT_SPOT: '0.01'
BOB_USDT_SPOT: '0.1'
BONK_USDT_SPOT: '0.1'
BTC3L_USDT_SPOT: '0.0001'
BTC3S_USDT_SPOT: '0.0001'
BTC_BRZ_SPOT: '0.00001'
BTC_DAI_SPOT: '0.000001'
BTC_EUR_SPOT: '0.000001'
BTC_USDC_SPOT: '0.000001'
BTC_USDT_SPOT: '0.000001'
BTG_USDT_SPOT: '0.001'
BTT_USDT_SPOT: '1'
BUSD_USDT_SPOT: '0.01'
C98_USDT_SPOT: '0.01'
CAKE_USDT_SPOT: '0.001'
CANDY_USDT_SPOT: '0.01'
CAPO_USDT_SPOT: '0.01'
CAPS_USDT_SPOT: '0.01'
CAT_USDT_SPOT: '0.01'
CBX_USDT_SPOT: '0.01'
CELO_USDT_SPOT: '0.01'
CEL_USDT_SPOT: '0.01'
CGPT_USDT_SPOT: '0.01'
CHRP_USDT_SPOT: '0.01'
CHZ_USDC_SPOT: '0.01'
CHZ_USDT_SPOT: '0.01'
CITY_USDT_SPOT: '0.01'
CMP_USDT_SPOT: '0.01'
COMP_USDT_SPOT: '0.001'
CORE_USDT_SPOT: '0.01'
COT_USDT_SPOT: '0.01'
CO_USDT_SPOT: '0.01'
CRV_USDT_SPOT: '0.01'
CTC_USDT_SPOT: '0.01'
CTT_USDT_SPOT: '0.01'
CULT_USDT_SPOT: '0.01'
CUSD_USDT_SPOT: '0.01'
CWAR_USDT_SPOT: '0.01'
CYBER_USDT_SPOT: '0.01'
DAI_USDT_SPOT: '0.01'
DCR_USDT_SPOT: '0.001'
DEFY_USDT_SPOT: '0.01'
DEVT_USDT_SPOT: '0.01'
DFI_USDT_SPOT: '0.01'
DGB_USDT_SPOT: '0.01'
DICE_USDT_SPOT: '0.01'
DLC_USDT_SPOT: '0.01'
DOGE2L_USDT_SPOT: '0.0001'
DOGE2S_USDT_SPOT: '0.0001'
DOGE_EUR_SPOT: '0.01'
DOGE_USDC_SPOT: '0.1'
DOGE_USDT_SPOT: '0.1'
DOME_USDT_SPOT: '0.01'
DOT3L_USDT_SPOT: '0.0001'
DOT3S_USDT_SPOT: '0.0001'
DOT_BTC_SPOT: '0.01'
DOT_USDC_SPOT: '0.001'
DOT_USDT_SPOT: '0.001'
DPX_USDT_SPOT: '0.001'
DSRUN_USDT_SPOT: '0.01'
DYDX_USDT_SPOT: '0.001'
DZOO_USDT_SPOT: '0.01'
ECOX_USDT_SPOT: '0.01'
EGLD_USDT_SPOT: '0.001'
EGO_USDT_SPOT: '0.01'
ELDA_USDT_SPOT: '0.01'
ELT_USDT_SPOT: '0.01'
ENJ_USDT_SPOT: '0.01'
ENS_USDT_SPOT: '0.01'
EOS2L_USDT_SPOT: '0.0001'
EOS2S_USDT_SPOT: '0.0001'
EOS_USDC_SPOT: '0.01'
EOS_USDT_SPOT: '0.01'
ERTHA_USDT_SPOT: '0.01'
ETC2L_USDT_SPOT: '0.0001'
ETC2S_USDT_SPOT: '0.0001'
ETC_USDT_SPOT: '0.01'
ETH3L_USDT_SPOT: '0.0001'
ETH3S_USDT_SPOT: '0.0001'
ETHW_USDT_SPOT: '0.01'
ETH_BTC_SPOT: '0.001'
ETH_DAI_SPOT: '0.00001'
ETH_EUR_SPOT: '0.00001'
ETH_USDC_SPOT: '0.00001'
ETH_USDT_SPOT: '0.00001'
EVER_USDT_SPOT: '0.01'
FAME_USDT_SPOT: '0.01'
FB_USDT_SPOT: '0.01'
FET_USDT_SPOT: '0.01'
FIDA_USDT_SPOT: '0.01'
FIL_USDC_SPOT: '0.01'
FIL_USDT_SPOT: '0.01'
FITFI_USDT_SPOT: '0.01'
FLOKI_USDT_SPOT: '0.1'
FLOW_USDT_SPOT: '0.01'
FLR_USDT_SPOT: '0.01'
FMB_USDT_SPOT: '0.01'
FON_USDT_SPOT: '0.01'
FORT_USDT_SPOT: '0.01'
FTM2L_USDT_SPOT: '0.0001'
FTM2S_USDT_SPOT: '0.0001'
FTM_USDT_SPOT: '0.01'
FTT_USDT_SPOT: '0.001'
FXS_USDT_SPOT: '0.01'
GALA_USDT_SPOT: '0.01'
GALFT_USDT_SPOT: '0.01'
GAL_USDT_SPOT: '0.01'
GCAKE_USDT_SPOT: '0.01'
GENE_USDT_SPOT: '0.01'
GGM_USDT_SPOT: '0.01'
GLMR_USDT_SPOT: '0.01'
GMT2L_USDT_SPOT: '0.0001'
GMT2S_USDT_SPOT: '0.0001'
GMT_USDC_SPOT: '0.01'
GMT_USDT_SPOT: '0.01'
GMX_USDT_SPOT: '0.01'
GM_USDT_SPOT: '0.1'
GNS_USDT_SPOT: '0.01'
GODS_USDT_SPOT: '0.01'
GPT_USDT_SPOT: '0.01'
GRT_USDT_SPOT: '0.01'
GSTS_USDT_SPOT: '0.01'
GST_USDT_SPOT: '0.01'
GSWIFT_USDT_SPOT: '0.01'
HBAR_USDT_SPOT: '0.01'
HERO_USDT_SPOT: '0.01'
HFT_USDC_SPOT: '0.01'
HFT_USDT_SPOT: '0.01'
HNT_USDT_SPOT: '0.001'
HOOK_USDT_SPOT: '0.01'
HOT_USDT_SPOT: '0.1'
HVH_USDT_SPOT: '0.01'
ICP_USDC_SPOT: '0.01'
ICP_USDT_SPOT: '0.01'
ICX_USDT_SPOT: '0.01'
ID_USDT_SPOT: '0.01'
IMX_USDT_SPOT: '0.01'
INJ_USDT_SPOT: '0.01'
INTER_USDT_SPOT: '0.01'
IZI_USDT_SPOT: '0.01'
JASMY_USDT_SPOT: '0.01'
JEFF_USDT_SPOT: '0.01'
JST_USDT_SPOT: '0.01'
JUV_USDT_SPOT: '0.01'
KARATE_USDT_SPOT: '0.01'
KASTA_USDT_SPOT: '0.1'
KAS_USDT_SPOT: '0.01'
KAVA_USDT_SPOT: '0.01'
KCAL_USDT_SPOT: '0.01'
KDA_USDT_SPOT: '0.01'
KLAY_USDT_SPOT: '0.01'
KMON_USDT_SPOT: '0.01'
KOK_USDT_SPOT: '0.01'
KON_USDT_SPOT: '0.01'
KRL_USDT_SPOT: '0.01'
KSM_USDT_SPOT: '0.001'
KUNCI_USDT_SPOT: '0.01'
LADYS_USDT_SPOT: '0.1'
LDO_USDC_SPOT: '0.01'
LDO_USDT_SPOT: '0.01'
LEVER_USDT_SPOT: '0.01'
LFW_USDT_SPOT: '0.01'
LGX_USDT_SPOT: '0.01'
LING_USDT_SPOT: '0.01'
LINK2L_USDT_SPOT: '0.0001'
LINK2S_USDT_SPOT: '0.0001'
LINK_USDC_SPOT: '0.001'
LINK_USDT_SPOT: '0.001'
LIS_USDT_SPOT: '0.01'
LMWR_USDT_SPOT: '0.01'
LOOKS_USDT_SPOT: '0.01'
LRC_USDT_SPOT: '0.01'
LTC2L_USDT_SPOT: '0.0001'
LTC2S_USDT_SPOT: '0.0001'
LTC_BTC_SPOT: '0.01'
LTC_EUR_SPOT: '0.00001'
LTC_USDC_SPOT: '0.00001'
LTC_USDT_SPOT: '0.00001'
LUNA_USDT_SPOT: '0.00001'
LUNC_USDC_SPOT: '0.001'
LUNC_USDT_SPOT: '0.001'
MAGIC_USDT_SPOT: '0.01'
MANA_BTC_SPOT: '0.1'
MANA_USDC_SPOT: '0.01'
MANA_USDT_SPOT: '0.01'
MASK_USDT_SPOT: '0.01'
MATIC2L_USDT_SPOT: '0.0001'
MATIC2S_USDT_SPOT: '0.0001'
MATIC_BTC_SPOT: '0.1'
MATIC_USDC_SPOT: '0.01'
MATIC_USDT_SPOT: '0.01'
MBS_USDT_SPOT: '0.01'
MBX_USDT_SPOT: '0.01'
MCRT_USDT_SPOT: '0.01'
MCT_USDT_SPOT: '0.01'
MDAO_USDT_SPOT: '0.01'
MEE_USDT_SPOT: '0.01'
MELOS_USDT_SPOT: '0.01'
MIBR_USDT_SPOT: '0.01'
MINA_USDT_SPOT: '0.01'
MIX_USDT_SPOT: '0.01'
MKR_USDT_SPOT: '0.0001'
MMC_USDT_SPOT: '0.01'
MNT_BTC_SPOT: '0.01'
MNT_USDC_SPOT: '0.01'
MNT_USDT_SPOT: '0.01'
MNZ_USDT_SPOT: '0.01'
MOVEZ_USDT_SPOT: '0.01'
MOVR_USDT_SPOT: '0.01'
MPLX_USDT_SPOT: '0.01'
MTC_USDT_SPOT: '0.01'
MTK_USDT_SPOT: '0.01'
MVL_USDT_SPOT: '0.01'
MV_USDT_SPOT: '0.01'
MX_USDT_SPOT: '0.01'
NEAR_USDT_SPOT: '0.01'
NEON_USDT_SPOT: '0.01'
NESS_USDT_SPOT: '0.01'
NEXO_USDT_SPOT: '0.01'
NEXT_USDT_SPOT: '0.01'
NFT_USDT_SPOT: '1'
NYM_USDT_SPOT: '0.01'
OAS_USDT_SPOT: '0.01'
OBX_USDT_SPOT: '0.01'
OKG_USDT_SPOT: '0.01'
OMG_USDT_SPOT: '0.001'
OMN_USDT_SPOT: '0.01'
ONE_USDT_SPOT: '0.01'
OP_USDC_SPOT: '0.01'
OP_USDT_SPOT: '0.01'
ORDI_USDT_SPOT: '0.01'
ORT_USDT_SPOT: '0.01'
PAXG_USDT_SPOT: '0.001'
PENDLE_USDT_SPOT: '0.01'
PEOPLE_USDT_SPOT: '0.01'
PEPE2_USDT_SPOT: '0.1'
PEPE_USDT_SPOT: '1'
PERP_USDT_SPOT: '0.01'
PIP_USDT_SPOT: '0.01'
PLANET_USDT_SPOT: '0.01'
PLAY_USDT_SPOT: '0.01'
PLT_USDT_SPOT: '0.01'
PLY_USDT_SPOT: '0.01'
POKT_USDT_SPOT: '0.01'
POL_USDT_SPOT: '0.01'
PPT_USDT_SPOT: '0.01'
PRIMAL_USDT_SPOT: '0.01'
PRIME_USDT_SPOT: '0.01'
PSG_USDT_SPOT: '0.01'
PSP_USDT_SPOT: '0.01'
PSTAKE_USDT_SPOT: '0.01'
PTU_USDT_SPOT: '0.001'
PUMLX_USDT_SPOT: '0.01'
PYUSD_USDT_SPOT: '0.01'
QMALL_USDT_SPOT: '0.01'
QNT_USDT_SPOT: '0.001'
QTUM_USDT_SPOT: '0.001'
RACA_USDT_SPOT: '0.01'
RAIN_USDT_SPOT: '0.1'
RDNT_USDT_SPOT: '0.01'
REAL_USDT_SPOT: '0.01'
REN_USDT_SPOT: '0.01'
RLTM_USDT_SPOT: '0.01'
RNDR_USDT_SPOT: '0.01'
ROND_USDT_SPOT: '0.01'
ROSE_USDT_SPOT: '0.01'
RPL_USDT_SPOT: '0.01'
RSS3_USDT_SPOT: '0.01'
RUNE_USDT_SPOT: '0.01'
RVN_USDT_SPOT: '0.1'
SAIL_USDT_SPOT: '0.01'
SAITAMA_USDT_SPOT: '0.01'
SALD_USDT_SPOT: '0.01'
SAND2L_USDT_SPOT: '0.0001'
SAND2S_USDT_SPOT: '0.0001'
SAND_BTC_SPOT: '0.1'
SAND_USDC_SPOT: '0.01'
SAND_USDT_SPOT: '0.01'
SCRT_USDT_SPOT: '0.01'
SC_USDT_SPOT: '0.01'
SD_USDT_SPOT: '0.01'
SEILOR_USDT_SPOT: '0.01'
SEI_USDT_SPOT: '0.01'
SEOR_USDT_SPOT: '0.01'
SFUND_USDT_SPOT: '0.01'
SHIB_USDC_SPOT: '0.1'
SHIB_USDT_SPOT: '0.1'
SHILL_USDT_SPOT: '0.01'
SIDUS_USDT_SPOT: '0.01'
SIS_USDT_SPOT: '0.01'
SLG_USDC_SPOT: '0.01'
SLG_USDT_SPOT: '0.01'
SLP_USDT_SPOT: '0.1'
SNX_USDT_SPOT: '0.01'
SOLO_USDT_SPOT: '0.01'
SOL_BTC_SPOT: '0.01'
SOL_EUR_SPOT: '0.001'
SOL_USDC_SPOT: '0.001'
SOL_USDT_SPOT: '0.001'
SON_USDT_SPOT: '0.01'
SOS_USDT_SPOT: '0.1'
SPARTA_USDT_SPOT: '0.01'
SPELL_USDT_SPOT: '0.1'
SRM_USDT_SPOT: '0.01'
SSV_USDT_SPOT: '0.01'
STAT_USDT_SPOT: '0.01'
STETH_USDT_SPOT: '0.00001'
STG_USDT_SPOT: '0.01'
STRM_USDT_SPOT: '0.01'
STX_USDT_SPOT: '0.01'
SUIA_USDT_SPOT: '0.01'
SUI_USDC_SPOT: '0.01'
SUI_USDT_SPOT: '0.01'
SUN_USDT_SPOT: '0.01'
SUSHI_USDT_SPOT: '0.001'
SWEAT_USDT_SPOT: '0.01'
SYNR_USDT_SPOT: '0.01'
TAMA_USDT_SPOT: '0.01'
TAP_USDT_SPOT: '0.01'
TAVA_USDT_SPOT: '0.01'
TEL_USDT_SPOT: '0.1'
TENET_USDT_SPOT: '0.01'
THETA_USDT_SPOT: '0.01'
THN_USDT_SPOT: '0.01'
TIA_USDT_SPOT: '0.01'
TIME_USDT_SPOT: '0.01'
TOMI_USDT_SPOT: '0.01'
TOMS_USDT_SPOT: '0.01'
TON_USDT_SPOT: '0.01'
TRIBE_USDT_SPOT: '0.01'
TRVL_USDT_SPOT: '0.01'
TRX_USDC_SPOT: '0.01'
TRX_USDT_SPOT: '0.01'
TURBOS_USDT_SPOT: '0.01'
TWT_USDT_SPOT: '0.01'
T_USDT_SPOT: '0.01'
UMA_USDT_SPOT: '0.001'
UNI_USDT_SPOT: '0.001'
USDC_EUR_SPOT: '0.01'
USDC_USDT_SPOT: '0.01'
USDD_USDT_SPOT: '0.01'
USDT_BRZ_SPOT: '0.01'
USDT_EUR_SPOT: '0.01'
USTC_USDT_SPOT: '0.01'
VEGA_USDT_SPOT: '0.01'
VELA_USDT_SPOT: '0.01'
VELO_USDT_SPOT: '0.01'
VEXT_USDT_SPOT: '0.01'
VINU_USDT_SPOT: '0.01'
VPAD_USDT_SPOT: '0.01'
VRA_USDT_SPOT: '0.01'
VV_USDT_SPOT: '0.01'
WAVES_USDT_SPOT: '0.01'
WAXP_USDT_SPOT: '0.01'
WBTC_BTC_SPOT: '0.0001'
WBTC_USDT_SPOT: '0.000001'
WEMIX_USDT_SPOT: '0.001'
WLD_USDC_SPOT: '0.01'
WLD_USDT_SPOT: '0.01'
WLKN_USDT_SPOT: '0.01'
WOO_USDT_SPOT: '0.01'
WWY_USDT_SPOT: '0.01'
XAVA_USDT_SPOT: '0.01'
XCAD_USDT_SPOT: '0.01'
XDC_USDT_SPOT: '0.1'
XEC_USDT_SPOT: '0.1'
XEM_USDT_SPOT: '0.01'
XETA_USDT_SPOT: '0.01'
XLM_BTC_SPOT: '0.1'
XLM_USDC_SPOT: '0.1'
XLM_USDT_SPOT: '0.1'
XRP3L_USDT_SPOT: '0.0001'
XRP3S_USDT_SPOT: '0.0001'
XRP_BTC_SPOT: '0.1'
XRP_EUR_SPOT: '0.01'
XRP_USDC_SPOT: '0.01'
XRP_USDT_SPOT: '0.01'
XTZ_USDT_SPOT: '0.01'
XWG_USDT_SPOT: '0.01'
XYM_USDT_SPOT: '0.01'
YFI_USDT_SPOT: '0.00001'
ZAM_USDT_SPOT: '0.01'
ZEN_USDT_SPOT: '0.001'
ZIL_USDT_SPOT: '0.1'
ZRX_USDT_SPOT: '0.01'
ZTX_USDT_SPOT: '0.01'
