10000LADYS_USDT_PERP: '100'
10000NFT_USDT_PERP: '10'
10000STARL_USDT_PERP: '10'
1000BONK_USDT_PERP: '100'
1000BTT_USDT_PERP: '100'
1000FLOKI_USDT_PERP: '1'
1000LUNC_USDT_PERP: '1'
1000PEPE_USDT_PERP: '100'
1000XEC_USDT_PERP: '10'
1INCH_USDT_PERP: '0.1'
AAVE_USDT_PERP: '0.01'
ACH_USDT_PERP: '10'
ADA_USDT_PERP: '1'
AGIX_USDT_PERP: '1'
AGLD_USDT_PERP: '0.1'
AKRO_USDT_PERP: '100'
ALGO_USDT_PERP: '0.1'
ALICE_USDT_PERP: '0.1'
ALPACA_USDT_PERP: '1'
ALPHA_USDT_PERP: '1'
AMB_USDT_PERP: '10'
ANKR_USDT_PERP: '1'
ANT_USDT_PERP: '0.1'
APE_USDT_PERP: '0.1'
API3_USDT_PERP: '0.1'
APT_USDT_PERP: '0.01'
ARB_USDT_PERP: '0.1'
ARKM_USDT_PERP: '1'
ARK_USDT_PERP: '1'
ARPA_USDT_PERP: '10'
AR_USDT_PERP: '0.1'
ASTR_USDT_PERP: '1'
ATA_USDT_PERP: '10'
ATOM_USDT_PERP: '0.1'
AUCTION_USDT_PERP: '0.1'
AUDIO_USDT_PERP: '0.1'
AVAX_USDT_PERP: '0.1'
AXS_USDT_PERP: '0.1'
BADGER_USDT_PERP: '0.1'
BAKE_USDT_PERP: '0.1'
BAL_USDT_PERP: '0.01'
BAND_USDT_PERP: '0.1'
BAT_USDT_PERP: '0.1'
BCH_USDT_PERP: '0.01'
BEL_USDT_PERP: '1'
BICO_USDT_PERP: '0.1'
BIGTIME_USDT_PERP: '1'
BLUR_USDT_PERP: '1'
BLZ_USDT_PERP: '1'
BNB_USDC_PERP: '0.01'
BNB_USDT_PERP: '0.01'
BNT_USDT_PERP: '1'
BNX_USDT_PERP: '0.1'
BOBA_USDT_PERP: '0.1'
BOND_USDT_PERP: '0.1'
BSV_USDT_PERP: '0.01'
BSW_USDT_PERP: '1'
BTC-03NOV23: '0.001'
BTC-10NOV23: '0.001'
BTC-17NOV23: '0.001'
BTC-24NOV23: '0.001'
BTC-28JUN24: '0.001'
BTC-29DEC23: '0.001'
BTC-29MAR24: '0.001'
BTC_USDC_PERP: '0.001'
BTC_USDT_PERP: '0.001'
BUSD_USDT_PERP: '0.1'
C98_USDT_PERP: '0.1'
CEEK_USDT_PERP: '1'
CELO_USDT_PERP: '0.1'
CELR_USDT_PERP: '1'
CFX_USDT_PERP: '1'
CHR_USDT_PERP: '0.1'
CHZ_USDT_PERP: '1'
CKB_USDT_PERP: '10'
COMBO_USDT_PERP: '0.1'
COMP_USDT_PERP: '0.01'
CORE_USDT_PERP: '0.1'
COTI_USDT_PERP: '1'
CRO_USDT_PERP: '1'
CRV_USDT_PERP: '0.1'
CTC_USDT_PERP: '1'
CTK_USDT_PERP: '0.1'
CTSI_USDT_PERP: '1'
CVC_USDT_PERP: '1'
CVX_USDT_PERP: '0.01'
CYBER_USDT_PERP: '0.1'
DAR_USDT_PERP: '0.1'
DASH_USDT_PERP: '0.01'
DENT_USDT_PERP: '100'
DGB_USDT_PERP: '10'
DODO_USDT_PERP: '1'
DOGE_USDT_PERP: '1'
DOT_USDT_PERP: '0.1'
DUSK_USDT_PERP: '1'
DYDX_USDT_PERP: '0.1'
EDU_USDT_PERP: '0.1'
EGLD_USDT_PERP: '0.01'
ENJ_USDT_PERP: '0.1'
ENS_USDT_PERP: '0.1'
EOS_USDT_PERP: '0.1'
ETC_USDC_PERP: '0.1'
ETC_USDT_PERP: '0.1'
ETH-03NOV23: '0.01'
ETH-10NOV23: '0.01'
ETH-17NOV23: '0.01'
ETH-24NOV23: '0.01'
ETH-28JUN24: '0.01'
ETH-29DEC23: '0.01'
ETH-29MAR24: '0.01'
ETHW_USDT_PERP: '0.01'
ETH_USDC_PERP: '0.01'
ETH_USDT_PERP: '0.01'
FET_USDT_PERP: '1'
FIL_USDT_PERP: '0.1'
FITFI_USDT_PERP: '1'
FLM_USDT_PERP: '1'
FLOW_USDT_PERP: '0.1'
FLR_USDT_PERP: '10'
FORTH_USDT_PERP: '0.1'
FRONT_USDT_PERP: '1'
FTM_USDT_PERP: '1'
FXS_USDT_PERP: '0.01'
GALA_USDT_PERP: '1'
GAL_USDT_PERP: '0.01'
GAS_USDT_PERP: '0.1'
GFT_USDT_PERP: '1'
GLMR_USDT_PERP: '0.1'
GLM_USDT_PERP: '1'
GMT_USDT_PERP: '1'
GMX_USDT_PERP: '0.01'
GPT_USDT_PERP: '1'
GRT_USDT_PERP: '0.1'
GTC_USDT_PERP: '0.1'
HBAR_USDT_PERP: '1'
HFT_USDT_PERP: '1'
HIFI_USDT_PERP: '1'
HIGH_USDT_PERP: '0.1'
HNT_USDT_PERP: '0.01'
HOOK_USDT_PERP: '0.1'
HOT_USDT_PERP: '100'
ICP_USDT_PERP: '0.1'
ICX_USDT_PERP: '1'
IDEX_USDT_PERP: '10'
ID_USDT_PERP: '1'
ILV_USDT_PERP: '0.01'
IMX_USDT_PERP: '0.1'
INJ_USDT_PERP: '0.1'
IOST_USDT_PERP: '1'
IOTA_USDT_PERP: '0.1'
IOTX_USDT_PERP: '1'
JASMY_USDT_PERP: '1'
JOE_USDT_PERP: '1'
JST_USDT_PERP: '10'
KAS_USDT_PERP: '10'
KAVA_USDT_PERP: '0.1'
KDA_USDT_PERP: '0.1'
KEY_USDT_PERP: '100'
KLAY_USDT_PERP: '0.1'
KNC_USDT_PERP: '0.1'
KSM_USDT_PERP: '0.01'
LDO_USDT_PERP: '0.1'
LEVER_USDT_PERP: '100'
LINA_USDT_PERP: '10'
LINK_USDT_PERP: '0.1'
LIT_USDT_PERP: '0.1'
LOOKS_USDT_PERP: '0.1'
LOOM_USDT_PERP: '10'
LPT_USDT_PERP: '0.1'
LQTY_USDT_PERP: '0.1'
LRC_USDT_PERP: '0.1'
LTC_USDT_PERP: '0.1'
LUNA2_USDT_PERP: '0.1'
MAGIC_USDT_PERP: '1'
MANA_USDT_PERP: '0.1'
MASK_USDT_PERP: '0.1'
MATIC_USDC_PERP: '1'
MATIC_USDT_PERP: '1'
MAV_USDT_PERP: '1'
MC_USDT_PERP: '1'
MDT_USDT_PERP: '10'
MINA_USDT_PERP: '0.1'
MKR_USDT_PERP: '0.001'
MNT_USDT_PERP: '1'
MTL_USDT_PERP: '0.1'
MULTI_USDT_PERP: '0.1'
NEAR_USDT_PERP: '0.1'
NEO_USDT_PERP: '0.01'
NKN_USDT_PERP: '1'
NMR_USDT_PERP: '0.1'
NTRN_USDT_PERP: '1'
OCEAN_USDT_PERP: '1'
OGN_USDT_PERP: '1'
OG_USDT_PERP: '0.1'
OMG_USDT_PERP: '0.1'
ONE_USDT_PERP: '1'
ONT_USDT_PERP: '1'
OP_USDC_PERP: '1'
OP_USDT_PERP: '0.1'
ORBS_USDT_PERP: '10'
ORDI_USDT_PERP: '0.01'
OXT_USDT_PERP: '10'
PAXG_USDT_PERP: '0.001'
PENDLE_USDT_PERP: '1'
PEOPLE_USDT_PERP: '1'
PERP_USDT_PERP: '1'
PHB_USDT_PERP: '1'
POLYX_USDT_PERP: '1'
POWR_USDT_PERP: '1'
PROM_USDT_PERP: '0.1'
QNT_USDT_PERP: '0.01'
QTUM_USDT_PERP: '0.1'
RAD_USDT_PERP: '0.1'
RDNT_USDT_PERP: '1'
REEF_USDT_PERP: '10'
REN_USDT_PERP: '0.1'
REQ_USDT_PERP: '1'
RIF_USDT_PERP: '1'
RLC_USDT_PERP: '0.1'
RNDR_USDT_PERP: '0.1'
ROSE_USDT_PERP: '1'
RPL_USDT_PERP: '0.01'
RSR_USDT_PERP: '10'
RSS3_USDT_PERP: '1'
RUNE_USDT_PERP: '0.1'
RVN_USDT_PERP: '1'
SAND_USDT_PERP: '1'
SCRT_USDT_PERP: '0.1'
SC_USDT_PERP: '10'
SEI_USDT_PERP: '1'
SFP_USDT_PERP: '0.1'
SHIB1000_USDT_PERP: '10'
SKL_USDT_PERP: '1'
SLP_USDT_PERP: '10'
SNX_USDT_PERP: '0.1'
SOL_USDC_PERP: '0.1'
SOL_USDT_PERP: '0.1'
SPELL_USDT_PERP: '10'
SSV_USDT_PERP: '0.01'
STEEM_USDT_PERP: '1'
STG_USDT_PERP: '0.1'
STMX_USDT_PERP: '5'
STORJ_USDT_PERP: '0.1'
STPT_USDT_PERP: '10'
STRAX_USDT_PERP: '1'
STX_USDT_PERP: '0.1'
SUI_USDT_PERP: '10'
SUN_USDT_PERP: '10'
SUSHI_USDT_PERP: '0.1'
SWEAT_USDT_PERP: '10'
SXP_USDT_PERP: '0.1'
THETA_USDT_PERP: '0.1'
TIA_USDT_PERP: '0.1'
TLM_USDT_PERP: '1'
TOMI_USDT_PERP: '0.1'
TOMO_USDT_PERP: '0.1'
TON_USDT_PERP: '0.1'
TRB_USDT_PERP: '0.01'
TRU_USDT_PERP: '1'
TRX_USDT_PERP: '1'
TWT_USDT_PERP: '0.1'
T_USDT_PERP: '10'
UMA_USDT_PERP: '0.1'
UNFI_USDT_PERP: '0.1'
UNI_USDT_PERP: '0.1'
USDC_USDT_PERP: '0.1'
VET_USDT_PERP: '1'
VGX_USDT_PERP: '1'
VRA_USDT_PERP: '100'
WAVES_USDT_PERP: '0.1'
WAXP_USDT_PERP: '10'
WLD_USDT_PERP: '0.1'
WOO_USDT_PERP: '0.1'
WSM_USDT_PERP: '10'
XCN_USDT_PERP: '10'
XEM_USDT_PERP: '1'
XLM_USDT_PERP: '1'
XMR_USDT_PERP: '0.01'
XNO_USDT_PERP: '1'
XRP_USDC_PERP: '1'
XRP_USDT_PERP: '1'
XTZ_USDT_PERP: '0.1'
XVG_USDT_PERP: '100'
XVS_USDT_PERP: '0.1'
YFII_USDT_PERP: '0.001'
YFI_USDT_PERP: '0.0001'
YGG_USDT_PERP: '0.1'
ZEC_USDT_PERP: '0.01'
ZEN_USDT_PERP: '0.1'
ZIL_USDT_PERP: '10'
ZRX_USDT_PERP: '1'
