10000LADYS_USDT_PERP: 10000LADYSUSDT
10000NFT_USDT_PERP: 10000NFTUSDT
10000STARL_USDT_PERP: 10000STARLUSDT
1000BONK_USDT_PERP: 1000BONKUSDT
1000BTT_USDT_PERP: 1000BTTUSDT
1000FLOKI_USDT_PERP: 1000FLOKIUSDT
1000LUNC_USDT_PERP: 1000LUNCUSDT
1000PEPE_USDT_PERP: 1000PEPEUSDT
1000XEC_USDT_PERP: 1000XECUSDT
1INCH_USDT_PERP: 1INCHUSDT
AAVE_USDT_PERP: AAVEUSDT
ACH_USDT_PERP: ACHUSDT
ADA_USDT_PERP: ADAUSDT
AGIX_USDT_PERP: AGIXUSDT
AGLD_USDT_PERP: AGLDUSDT
AKRO_USDT_PERP: AKROUSDT
ALGO_USDT_PERP: ALGOUSDT
ALICE_USDT_PERP: ALICEUSDT
ALPACA_USDT_PERP: ALPACAUSDT
ALPHA_USDT_PERP: ALPHAUSDT
AMB_USDT_PERP: AMBUSDT
ANKR_USDT_PERP: ANKRUSDT
ANT_USDT_PERP: ANTUSDT
APE_USDT_PERP: APEUSDT
API3_USDT_PERP: API3USDT
APT_USDT_PERP: APTUSDT
ARB_USDT_PERP: ARBUSDT
ARKM_USDT_PERP: ARKMUSDT
ARK_USDT_PERP: ARKUSDT
ARPA_USDT_PERP: ARPAUSDT
AR_USDT_PERP: ARUSDT
ASTR_USDT_PERP: ASTRUSDT
ATA_USDT_PERP: ATAUSDT
ATOM_USDT_PERP: ATOMUSDT
AUCTION_USDT_PERP: AUCTIONUSDT
AUDIO_USDT_PERP: AUDIOUSDT
AVAX_USDT_PERP: AVAXUSDT
AXS_USDT_PERP: AXSUSDT
BADGER_USDT_PERP: BADGERUSDT
BAKE_USDT_PERP: BAKEUSDT
BAL_USDT_PERP: BALUSDT
BAND_USDT_PERP: BANDUSDT
BAT_USDT_PERP: BATUSDT
BCH_USDT_PERP: BCHUSDT
BEL_USDT_PERP: BELUSDT
BICO_USDT_PERP: BICOUSDT
BIGTIME_USDT_PERP: BIGTIMEUSDT
BLUR_USDT_PERP: BLURUSDT
BLZ_USDT_PERP: BLZUSDT
BNB_USDC_PERP: BNBPERP
BNB_USDT_PERP: BNBUSDT
BNT_USDT_PERP: BNTUSDT
BNX_USDT_PERP: BNXUSDT
BOBA_USDT_PERP: BOBAUSDT
BOND_USDT_PERP: BONDUSDT
BSV_USDT_PERP: BSVUSDT
BSW_USDT_PERP: BSWUSDT
BTC_USDC_PERP: BTCPERP
BTC_USDT_PERP: BTCUSDT
BUSD_USDT_PERP: BUSDUSDT
C98_USDT_PERP: C98USDT
CEEK_USDT_PERP: CEEKUSDT
CELO_USDT_PERP: CELOUSDT
CELR_USDT_PERP: CELRUSDT
CFX_USDT_PERP: CFXUSDT
CHR_USDT_PERP: CHRUSDT
CHZ_USDT_PERP: CHZUSDT
CKB_USDT_PERP: CKBUSDT
COMBO_USDT_PERP: COMBOUSDT
COMP_USDT_PERP: COMPUSDT
CORE_USDT_PERP: COREUSDT
COTI_USDT_PERP: COTIUSDT
CRO_USDT_PERP: CROUSDT
CRV_USDT_PERP: CRVUSDT
CTC_USDT_PERP: CTCUSDT
CTK_USDT_PERP: CTKUSDT
CTSI_USDT_PERP: CTSIUSDT
CVC_USDT_PERP: CVCUSDT
CVX_USDT_PERP: CVXUSDT
CYBER_USDT_PERP: CYBERUSDT
DAR_USDT_PERP: DARUSDT
DASH_USDT_PERP: DASHUSDT
DENT_USDT_PERP: DENTUSDT
DGB_USDT_PERP: DGBUSDT
DODO_USDT_PERP: DODOUSDT
DOGE_USDT_PERP: DOGEUSDT
DOT_USDT_PERP: DOTUSDT
DUSK_USDT_PERP: DUSKUSDT
DYDX_USDT_PERP: DYDXUSDT
EDU_USDT_PERP: EDUUSDT
EGLD_USDT_PERP: EGLDUSDT
ENJ_USDT_PERP: ENJUSDT
ENS_USDT_PERP: ENSUSDT
EOS_USDT_PERP: EOSUSDT
ETC_USDC_PERP: ETCPERP
ETC_USDT_PERP: ETCUSDT
ETHW_USDT_PERP: ETHWUSDT
ETH_USDC_PERP: ETHPERP
ETH_USDT_PERP: ETHUSDT
FET_USDT_PERP: FETUSDT
FIL_USDT_PERP: FILUSDT
FITFI_USDT_PERP: FITFIUSDT
FLM_USDT_PERP: FLMUSDT
FLOW_USDT_PERP: FLOWUSDT
FLR_USDT_PERP: FLRUSDT
FORTH_USDT_PERP: FORTHUSDT
FRONT_USDT_PERP: FRONTUSDT
FTM_USDT_PERP: FTMUSDT
FXS_USDT_PERP: FXSUSDT
GALA_USDT_PERP: GALAUSDT
GAL_USDT_PERP: GALUSDT
GAS_USDT_PERP: GASUSDT
GFT_USDT_PERP: GFTUSDT
GLMR_USDT_PERP: GLMRUSDT
GLM_USDT_PERP: GLMUSDT
GMT_USDT_PERP: GMTUSDT
GMX_USDT_PERP: GMXUSDT
GPT_USDT_PERP: GPTUSDT
GRT_USDT_PERP: GRTUSDT
GTC_USDT_PERP: GTCUSDT
HBAR_USDT_PERP: HBARUSDT
HFT_USDT_PERP: HFTUSDT
HIFI_USDT_PERP: HIFIUSDT
HIGH_USDT_PERP: HIGHUSDT
HNT_USDT_PERP: HNTUSDT
HOOK_USDT_PERP: HOOKUSDT
HOT_USDT_PERP: HOTUSDT
ICP_USDT_PERP: ICPUSDT
ICX_USDT_PERP: ICXUSDT
IDEX_USDT_PERP: IDEXUSDT
ID_USDT_PERP: IDUSDT
ILV_USDT_PERP: ILVUSDT
IMX_USDT_PERP: IMXUSDT
INJ_USDT_PERP: INJUSDT
IOST_USDT_PERP: IOSTUSDT
IOTA_USDT_PERP: IOTAUSDT
IOTX_USDT_PERP: IOTXUSDT
JASMY_USDT_PERP: JASMYUSDT
JOE_USDT_PERP: JOEUSDT
JST_USDT_PERP: JSTUSDT
KAS_USDT_PERP: KASUSDT
KAVA_USDT_PERP: KAVAUSDT
KDA_USDT_PERP: KDAUSDT
KEY_USDT_PERP: KEYUSDT
KLAY_USDT_PERP: KLAYUSDT
KNC_USDT_PERP: KNCUSDT
KSM_USDT_PERP: KSMUSDT
LDO_USDT_PERP: LDOUSDT
LEVER_USDT_PERP: LEVERUSDT
LINA_USDT_PERP: LINAUSDT
LINK_USDT_PERP: LINKUSDT
LIT_USDT_PERP: LITUSDT
LOOKS_USDT_PERP: LOOKSUSDT
LOOM_USDT_PERP: LOOMUSDT
LPT_USDT_PERP: LPTUSDT
LQTY_USDT_PERP: LQTYUSDT
LRC_USDT_PERP: LRCUSDT
LTC_USDT_PERP: LTCUSDT
LUNA2_USDT_PERP: LUNA2USDT
MAGIC_USDT_PERP: MAGICUSDT
MANA_USDT_PERP: MANAUSDT
MASK_USDT_PERP: MASKUSDT
MATIC_USDC_PERP: MATICPERP
MATIC_USDT_PERP: MATICUSDT
MAV_USDT_PERP: MAVUSDT
MC_USDT_PERP: MCUSDT
MDT_USDT_PERP: MDTUSDT
MINA_USDT_PERP: MINAUSDT
MKR_USDT_PERP: MKRUSDT
MNT_USDT_PERP: MNTUSDT
MTL_USDT_PERP: MTLUSDT
MULTI_USDT_PERP: MULTIUSDT
NEAR_USDT_PERP: NEARUSDT
NEO_USDT_PERP: NEOUSDT
NKN_USDT_PERP: NKNUSDT
NMR_USDT_PERP: NMRUSDT
NTRN_USDT_PERP: NTRNUSDT
OCEAN_USDT_PERP: OCEANUSDT
OGN_USDT_PERP: OGNUSDT
OG_USDT_PERP: OGUSDT
OMG_USDT_PERP: OMGUSDT
ONE_USDT_PERP: ONEUSDT
ONT_USDT_PERP: ONTUSDT
OP_USDC_PERP: OPPERP
OP_USDT_PERP: OPUSDT
ORBS_USDT_PERP: ORBSUSDT
ORDI_USDT_PERP: ORDIUSDT
OXT_USDT_PERP: OXTUSDT
PAXG_USDT_PERP: PAXGUSDT
PENDLE_USDT_PERP: PENDLEUSDT
PEOPLE_USDT_PERP: PEOPLEUSDT
PERP_USDT_PERP: PERPUSDT
PHB_USDT_PERP: PHBUSDT
POLYX_USDT_PERP: POLYXUSDT
POWR_USDT_PERP: POWRUSDT
PROM_USDT_PERP: PROMUSDT
QNT_USDT_PERP: QNTUSDT
QTUM_USDT_PERP: QTUMUSDT
RAD_USDT_PERP: RADUSDT
RDNT_USDT_PERP: RDNTUSDT
REEF_USDT_PERP: REEFUSDT
REN_USDT_PERP: RENUSDT
REQ_USDT_PERP: REQUSDT
RIF_USDT_PERP: RIFUSDT
RLC_USDT_PERP: RLCUSDT
RNDR_USDT_PERP: RNDRUSDT
ROSE_USDT_PERP: ROSEUSDT
RPL_USDT_PERP: RPLUSDT
RSR_USDT_PERP: RSRUSDT
RSS3_USDT_PERP: RSS3USDT
RUNE_USDT_PERP: RUNEUSDT
RVN_USDT_PERP: RVNUSDT
SAND_USDT_PERP: SANDUSDT
SCRT_USDT_PERP: SCRTUSDT
SC_USDT_PERP: SCUSDT
SEI_USDT_PERP: SEIUSDT
SFP_USDT_PERP: SFPUSDT
SHIB1000_USDT_PERP: SHIB1000USDT
SKL_USDT_PERP: SKLUSDT
SLP_USDT_PERP: SLPUSDT
SNX_USDT_PERP: SNXUSDT
SOL_USDC_PERP: SOLPERP
SOL_USDT_PERP: SOLUSDT
SPELL_USDT_PERP: SPELLUSDT
SSV_USDT_PERP: SSVUSDT
STEEM_USDT_PERP: STEEMUSDT
STG_USDT_PERP: STGUSDT
STMX_USDT_PERP: STMXUSDT
STORJ_USDT_PERP: STORJUSDT
STPT_USDT_PERP: STPTUSDT
STRAX_USDT_PERP: STRAXUSDT
STX_USDT_PERP: STXUSDT
SUI_USDT_PERP: SUIUSDT
SUN_USDT_PERP: SUNUSDT
SUSHI_USDT_PERP: SUSHIUSDT
SWEAT_USDT_PERP: SWEATUSDT
SXP_USDT_PERP: SXPUSDT
THETA_USDT_PERP: THETAUSDT
TIA_USDT_PERP: TIAUSDT
TLM_USDT_PERP: TLMUSDT
TOMI_USDT_PERP: TOMIUSDT
TOMO_USDT_PERP: TOMOUSDT
TON_USDT_PERP: TONUSDT
TRB_USDT_PERP: TRBUSDT
TRU_USDT_PERP: TRUUSDT
TRX_USDT_PERP: TRXUSDT
TWT_USDT_PERP: TWTUSDT
T_USDT_PERP: TUSDT
UMA_USDT_PERP: UMAUSDT
UNFI_USDT_PERP: UNFIUSDT
UNI_USDT_PERP: UNIUSDT
USDC_USDT_PERP: USDCUSDT
VET_USDT_PERP: VETUSDT
VGX_USDT_PERP: VGXUSDT
VRA_USDT_PERP: VRAUSDT
WAVES_USDT_PERP: WAVESUSDT
WAXP_USDT_PERP: WAXPUSDT
WLD_USDT_PERP: WLDUSDT
WOO_USDT_PERP: WOOUSDT
WSM_USDT_PERP: WSMUSDT
XCN_USDT_PERP: XCNUSDT
XEM_USDT_PERP: XEMUSDT
XLM_USDT_PERP: XLMUSDT
XMR_USDT_PERP: XMRUSDT
XNO_USDT_PERP: XNOUSDT
XRP_USDC_PERP: XRPPERP
XRP_USDT_PERP: XRPUSDT
XTZ_USDT_PERP: XTZUSDT
XVG_USDT_PERP: XVGUSDT
XVS_USDT_PERP: XVSUSDT
YFII_USDT_PERP: YFIIUSDT
YFI_USDT_PERP: YFIUSDT
YGG_USDT_PERP: YGGUSDT
ZEC_USDT_PERP: ZECUSDT
ZEN_USDT_PERP: ZENUSDT
ZIL_USDT_PERP: ZILUSDT
ZRX_USDT_PERP: ZRXUSDT
