1INCH_USDT_SPOT: 1INCHUSDT
1SOL_USDT_SPOT: 1SOLUSDT
3P_USDT_SPOT: 3PUSDT
AAVE_USDT_SPOT: AAVEUSDT
ACA_USDT_SPOT: ACAUSDT
ACH_USDT_SPOT: ACHUSDT
ACM_USDT_SPOT: ACMUSDT
ACS_USDT_SPOT: ACSUSDT
ADA2L_USDT_SPOT: ADA2LUSDT
ADA2S_USDT_SPOT: ADA2SUSDT
ADA_EUR_SPOT: ADAEUR
ADA_USDC_SPOT: ADAUSDC
ADA_USDT_SPOT: ADAUSDT
AFC_USDT_SPOT: AFCUSDT
AGIX_USDT_SPOT: AGIXUSDT
AGI_USDT_SPOT: AGIUSDT
AGLA_USDT_SPOT: AGLAUSDT
AGLD_USDT_SPOT: AGLDUSDT
ALGO_BTC_SPOT: ALGOBTC
ALGO_USDT_SPOT: ALGOUSDT
ANKR_USDT_SPOT: ANKRUSDT
APE2L_USDT_SPOT: APE2LUSDT
APE2S_USDT_SPOT: APE2SUSDT
APEX_USDC_SPOT: APEXUSDC
APEX_USDT_SPOT: APEXUSDT
APE_USDC_SPOT: APEUSDC
APE_USDT_SPOT: APEUSDT
APT_USDC_SPOT: APTUSDC
APT_USDT_SPOT: APTUSDT
ARB_USDC_SPOT: ARBUSDC
ARB_USDT_SPOT: ARBUSDT
ARKM_USDT_SPOT: ARKMUSDT
AR_USDT_SPOT: ARUSDT
ATOM2L_USDT_SPOT: ATOM2LUSDT
ATOM2S_USDT_SPOT: ATOM2SUSDT
ATOM_USDT_SPOT: ATOMUSDT
AVAX2L_USDT_SPOT: AVAX2LUSDT
AVAX2S_USDT_SPOT: AVAX2SUSDT
AVAX_USDC_SPOT: AVAXUSDC
AVAX_USDT_SPOT: AVAXUSDT
AVA_USDT_SPOT: AVAUSDT
AXL_USDT_SPOT: AXLUSDT
AXS_USDT_SPOT: AXSUSDT
AZY_USDT_SPOT: AZYUSDT
BABYDOGE_USDT_SPOT: BABYDOGEUSDT
BAR_USDT_SPOT: BARUSDT
BAT_USDT_SPOT: BATUSDT
BCH_USDT_SPOT: BCHUSDT
BEAM_USDT_SPOT: BEAMUSDT
BEL_USDT_SPOT: BELUSDT
BICO_USDT_SPOT: BICOUSDT
BLUR_USDT_SPOT: BLURUSDT
BNB_USDT_SPOT: BNBUSDT
BNT_USDT_SPOT: BNTUSDT
BOBA_USDT_SPOT: BOBAUSDT
BOB_USDT_SPOT: BOBUSDT
BONK_USDT_SPOT: BONKUSDT
BTC3L_USDT_SPOT: BTC3LUSDT
BTC3S_USDT_SPOT: BTC3SUSDT
BTC_BRZ_SPOT: BTCBRZ
BTC_DAI_SPOT: BTCDAI
BTC_EUR_SPOT: BTCEUR
BTC_USDC_SPOT: BTCUSDC
BTC_USDT_SPOT: BTCUSDT
BTG_USDT_SPOT: BTGUSDT
BTT_USDT_SPOT: BTTUSDT
BUSD_USDT_SPOT: BUSDUSDT
C98_USDT_SPOT: C98USDT
CAKE_USDT_SPOT: CAKEUSDT
CANDY_USDT_SPOT: CANDYUSDT
CAPO_USDT_SPOT: CAPOUSDT
CAPS_USDT_SPOT: CAPSUSDT
CAT_USDT_SPOT: CATUSDT
CBX_USDT_SPOT: CBXUSDT
CELO_USDT_SPOT: CELOUSDT
CEL_USDT_SPOT: CELUSDT
CGPT_USDT_SPOT: CGPTUSDT
CHRP_USDT_SPOT: CHRPUSDT
CHZ_USDC_SPOT: CHZUSDC
CHZ_USDT_SPOT: CHZUSDT
CITY_USDT_SPOT: CITYUSDT
CMP_USDT_SPOT: CMPUSDT
COMP_USDT_SPOT: COMPUSDT
CORE_USDT_SPOT: COREUSDT
COT_USDT_SPOT: COTUSDT
CO_USDT_SPOT: COUSDT
CRV_USDT_SPOT: CRVUSDT
CTC_USDT_SPOT: CTCUSDT
CTT_USDT_SPOT: CTTUSDT
CULT_USDT_SPOT: CULTUSDT
CUSD_USDT_SPOT: CUSDUSDT
CWAR_USDT_SPOT: CWARUSDT
CYBER_USDT_SPOT: CYBERUSDT
DAI_USDT_SPOT: DAIUSDT
DCR_USDT_SPOT: DCRUSDT
DEFY_USDT_SPOT: DEFYUSDT
DEVT_USDT_SPOT: DEVTUSDT
DFI_USDT_SPOT: DFIUSDT
DGB_USDT_SPOT: DGBUSDT
DICE_USDT_SPOT: DICEUSDT
DLC_USDT_SPOT: DLCUSDT
DOGE2L_USDT_SPOT: DOGE2LUSDT
DOGE2S_USDT_SPOT: DOGE2SUSDT
DOGE_EUR_SPOT: DOGEEUR
DOGE_USDC_SPOT: DOGEUSDC
DOGE_USDT_SPOT: DOGEUSDT
DOME_USDT_SPOT: DOMEUSDT
DOT3L_USDT_SPOT: DOT3LUSDT
DOT3S_USDT_SPOT: DOT3SUSDT
DOT_BTC_SPOT: DOTBTC
DOT_USDC_SPOT: DOTUSDC
DOT_USDT_SPOT: DOTUSDT
DPX_USDT_SPOT: DPXUSDT
DSRUN_USDT_SPOT: DSRUNUSDT
DYDX_USDT_SPOT: DYDXUSDT
DZOO_USDT_SPOT: DZOOUSDT
ECOX_USDT_SPOT: ECOXUSDT
EGLD_USDT_SPOT: EGLDUSDT
EGO_USDT_SPOT: EGOUSDT
ELDA_USDT_SPOT: ELDAUSDT
ELT_USDT_SPOT: ELTUSDT
ENJ_USDT_SPOT: ENJUSDT
ENS_USDT_SPOT: ENSUSDT
EOS2L_USDT_SPOT: EOS2LUSDT
EOS2S_USDT_SPOT: EOS2SUSDT
EOS_USDC_SPOT: EOSUSDC
EOS_USDT_SPOT: EOSUSDT
ERTHA_USDT_SPOT: ERTHAUSDT
ETC2L_USDT_SPOT: ETC2LUSDT
ETC2S_USDT_SPOT: ETC2SUSDT
ETC_USDT_SPOT: ETCUSDT
ETH3L_USDT_SPOT: ETH3LUSDT
ETH3S_USDT_SPOT: ETH3SUSDT
ETHW_USDT_SPOT: ETHWUSDT
ETH_BTC_SPOT: ETHBTC
ETH_DAI_SPOT: ETHDAI
ETH_EUR_SPOT: ETHEUR
ETH_USDC_SPOT: ETHUSDC
ETH_USDT_SPOT: ETHUSDT
EVER_USDT_SPOT: EVERUSDT
FAME_USDT_SPOT: FAMEUSDT
FB_USDT_SPOT: FBUSDT
FET_USDT_SPOT: FETUSDT
FIDA_USDT_SPOT: FIDAUSDT
FIL_USDC_SPOT: FILUSDC
FIL_USDT_SPOT: FILUSDT
FITFI_USDT_SPOT: FITFIUSDT
FLOKI_USDT_SPOT: FLOKIUSDT
FLOW_USDT_SPOT: FLOWUSDT
FLR_USDT_SPOT: FLRUSDT
FMB_USDT_SPOT: FMBUSDT
FON_USDT_SPOT: FONUSDT
FORT_USDT_SPOT: FORTUSDT
FTM2L_USDT_SPOT: FTM2LUSDT
FTM2S_USDT_SPOT: FTM2SUSDT
FTM_USDT_SPOT: FTMUSDT
FTT_USDT_SPOT: FTTUSDT
FXS_USDT_SPOT: FXSUSDT
GALA_USDT_SPOT: GALAUSDT
GALFT_USDT_SPOT: GALFTUSDT
GAL_USDT_SPOT: GALUSDT
GCAKE_USDT_SPOT: GCAKEUSDT
GENE_USDT_SPOT: GENEUSDT
GGM_USDT_SPOT: GGMUSDT
GLMR_USDT_SPOT: GLMRUSDT
GMT2L_USDT_SPOT: GMT2LUSDT
GMT2S_USDT_SPOT: GMT2SUSDT
GMT_USDC_SPOT: GMTUSDC
GMT_USDT_SPOT: GMTUSDT
GMX_USDT_SPOT: GMXUSDT
GM_USDT_SPOT: GMUSDT
GNS_USDT_SPOT: GNSUSDT
GODS_USDT_SPOT: GODSUSDT
GPT_USDT_SPOT: GPTUSDT
GRT_USDT_SPOT: GRTUSDT
GSTS_USDT_SPOT: GSTSUSDT
GST_USDT_SPOT: GSTUSDT
GSWIFT_USDT_SPOT: GSWIFTUSDT
HBAR_USDT_SPOT: HBARUSDT
HERO_USDT_SPOT: HEROUSDT
HFT_USDC_SPOT: HFTUSDC
HFT_USDT_SPOT: HFTUSDT
HNT_USDT_SPOT: HNTUSDT
HOOK_USDT_SPOT: HOOKUSDT
HOT_USDT_SPOT: HOTUSDT
HVH_USDT_SPOT: HVHUSDT
ICP_USDC_SPOT: ICPUSDC
ICP_USDT_SPOT: ICPUSDT
ICX_USDT_SPOT: ICXUSDT
ID_USDT_SPOT: IDUSDT
IMX_USDT_SPOT: IMXUSDT
INJ_USDT_SPOT: INJUSDT
INTER_USDT_SPOT: INTERUSDT
IZI_USDT_SPOT: IZIUSDT
JASMY_USDT_SPOT: JASMYUSDT
JEFF_USDT_SPOT: JEFFUSDT
JST_USDT_SPOT: JSTUSDT
JUV_USDT_SPOT: JUVUSDT
KARATE_USDT_SPOT: KARATEUSDT
KASTA_USDT_SPOT: KASTAUSDT
KAS_USDT_SPOT: KASUSDT
KAVA_USDT_SPOT: KAVAUSDT
KCAL_USDT_SPOT: KCALUSDT
KDA_USDT_SPOT: KDAUSDT
KLAY_USDT_SPOT: KLAYUSDT
KMON_USDT_SPOT: KMONUSDT
KOK_USDT_SPOT: KOKUSDT
KON_USDT_SPOT: KONUSDT
KRL_USDT_SPOT: KRLUSDT
KSM_USDT_SPOT: KSMUSDT
KUNCI_USDT_SPOT: KUNCIUSDT
LADYS_USDT_SPOT: LADYSUSDT
LDO_USDC_SPOT: LDOUSDC
LDO_USDT_SPOT: LDOUSDT
LEVER_USDT_SPOT: LEVERUSDT
LFW_USDT_SPOT: LFWUSDT
LGX_USDT_SPOT: LGXUSDT
LING_USDT_SPOT: LINGUSDT
LINK2L_USDT_SPOT: LINK2LUSDT
LINK2S_USDT_SPOT: LINK2SUSDT
LINK_USDC_SPOT: LINKUSDC
LINK_USDT_SPOT: LINKUSDT
LIS_USDT_SPOT: LISUSDT
LMWR_USDT_SPOT: LMWRUSDT
LOOKS_USDT_SPOT: LOOKSUSDT
LRC_USDT_SPOT: LRCUSDT
LTC2L_USDT_SPOT: LTC2LUSDT
LTC2S_USDT_SPOT: LTC2SUSDT
LTC_BTC_SPOT: LTCBTC
LTC_EUR_SPOT: LTCEUR
LTC_USDC_SPOT: LTCUSDC
LTC_USDT_SPOT: LTCUSDT
LUNA_USDT_SPOT: LUNAUSDT
LUNC_USDC_SPOT: LUNCUSDC
LUNC_USDT_SPOT: LUNCUSDT
MAGIC_USDT_SPOT: MAGICUSDT
MANA_BTC_SPOT: MANABTC
MANA_USDC_SPOT: MANAUSDC
MANA_USDT_SPOT: MANAUSDT
MASK_USDT_SPOT: MASKUSDT
MATIC2L_USDT_SPOT: MATIC2LUSDT
MATIC2S_USDT_SPOT: MATIC2SUSDT
MATIC_BTC_SPOT: MATICBTC
MATIC_USDC_SPOT: MATICUSDC
MATIC_USDT_SPOT: MATICUSDT
MBS_USDT_SPOT: MBSUSDT
MBX_USDT_SPOT: MBXUSDT
MCRT_USDT_SPOT: MCRTUSDT
MCT_USDT_SPOT: MCTUSDT
MDAO_USDT_SPOT: MDAOUSDT
MEE_USDT_SPOT: MEEUSDT
MELOS_USDT_SPOT: MELOSUSDT
MIBR_USDT_SPOT: MIBRUSDT
MINA_USDT_SPOT: MINAUSDT
MIX_USDT_SPOT: MIXUSDT
MKR_USDT_SPOT: MKRUSDT
MMC_USDT_SPOT: MMCUSDT
MNT_BTC_SPOT: MNTBTC
MNT_USDC_SPOT: MNTUSDC
MNT_USDT_SPOT: MNTUSDT
MNZ_USDT_SPOT: MNZUSDT
MOVEZ_USDT_SPOT: MOVEZUSDT
MOVR_USDT_SPOT: MOVRUSDT
MPLX_USDT_SPOT: MPLXUSDT
MTC_USDT_SPOT: MTCUSDT
MTK_USDT_SPOT: MTKUSDT
MVL_USDT_SPOT: MVLUSDT
MV_USDT_SPOT: MVUSDT
MX_USDT_SPOT: MXUSDT
NEAR_USDT_SPOT: NEARUSDT
NEON_USDT_SPOT: NEONUSDT
NESS_USDT_SPOT: NESSUSDT
NEXO_USDT_SPOT: NEXOUSDT
NEXT_USDT_SPOT: NEXTUSDT
NFT_USDT_SPOT: NFTUSDT
NYM_USDT_SPOT: NYMUSDT
OAS_USDT_SPOT: OASUSDT
OBX_USDT_SPOT: OBXUSDT
OKG_USDT_SPOT: OKGUSDT
OMG_USDT_SPOT: OMGUSDT
OMN_USDT_SPOT: OMNUSDT
ONE_USDT_SPOT: ONEUSDT
OP_USDC_SPOT: OPUSDC
OP_USDT_SPOT: OPUSDT
ORDI_USDT_SPOT: ORDIUSDT
ORT_USDT_SPOT: ORTUSDT
PAXG_USDT_SPOT: PAXGUSDT
PENDLE_USDT_SPOT: PENDLEUSDT
PEOPLE_USDT_SPOT: PEOPLEUSDT
PEPE2_USDT_SPOT: PEPE2USDT
PEPE_USDT_SPOT: PEPEUSDT
PERP_USDT_SPOT: PERPUSDT
PIP_USDT_SPOT: PIPUSDT
PLANET_USDT_SPOT: PLANETUSDT
PLAY_USDT_SPOT: PLAYUSDT
PLT_USDT_SPOT: PLTUSDT
PLY_USDT_SPOT: PLYUSDT
POKT_USDT_SPOT: POKTUSDT
POL_USDT_SPOT: POLUSDT
PPT_USDT_SPOT: PPTUSDT
PRIMAL_USDT_SPOT: PRIMALUSDT
PRIME_USDT_SPOT: PRIMEUSDT
PSG_USDT_SPOT: PSGUSDT
PSP_USDT_SPOT: PSPUSDT
PSTAKE_USDT_SPOT: PSTAKEUSDT
PTU_USDT_SPOT: PTUUSDT
PUMLX_USDT_SPOT: PUMLXUSDT
PYUSD_USDT_SPOT: PYUSDUSDT
QMALL_USDT_SPOT: QMALLUSDT
QNT_USDT_SPOT: QNTUSDT
QTUM_USDT_SPOT: QTUMUSDT
RACA_USDT_SPOT: RACAUSDT
RAIN_USDT_SPOT: RAINUSDT
RDNT_USDT_SPOT: RDNTUSDT
REAL_USDT_SPOT: REALUSDT
REN_USDT_SPOT: RENUSDT
RLTM_USDT_SPOT: RLTMUSDT
RNDR_USDT_SPOT: RNDRUSDT
ROND_USDT_SPOT: RONDUSDT
ROSE_USDT_SPOT: ROSEUSDT
RPL_USDT_SPOT: RPLUSDT
RSS3_USDT_SPOT: RSS3USDT
RUNE_USDT_SPOT: RUNEUSDT
RVN_USDT_SPOT: RVNUSDT
SAIL_USDT_SPOT: SAILUSDT
SAITAMA_USDT_SPOT: SAITAMAUSDT
SALD_USDT_SPOT: SALDUSDT
SAND2L_USDT_SPOT: SAND2LUSDT
SAND2S_USDT_SPOT: SAND2SUSDT
SAND_BTC_SPOT: SANDBTC
SAND_USDC_SPOT: SANDUSDC
SAND_USDT_SPOT: SANDUSDT
SCRT_USDT_SPOT: SCRTUSDT
SC_USDT_SPOT: SCUSDT
SD_USDT_SPOT: SDUSDT
SEILOR_USDT_SPOT: SEILORUSDT
SEI_USDT_SPOT: SEIUSDT
SEOR_USDT_SPOT: SEORUSDT
SFUND_USDT_SPOT: SFUNDUSDT
SHIB_USDC_SPOT: SHIBUSDC
SHIB_USDT_SPOT: SHIBUSDT
SHILL_USDT_SPOT: SHILLUSDT
SIDUS_USDT_SPOT: SIDUSUSDT
SIS_USDT_SPOT: SISUSDT
SLG_USDC_SPOT: SLGUSDC
SLG_USDT_SPOT: SLGUSDT
SLP_USDT_SPOT: SLPUSDT
SNX_USDT_SPOT: SNXUSDT
SOLO_USDT_SPOT: SOLOUSDT
SOL_BTC_SPOT: SOLBTC
SOL_EUR_SPOT: SOLEUR
SOL_USDC_SPOT: SOLUSDC
SOL_USDT_SPOT: SOLUSDT
SON_USDT_SPOT: SONUSDT
SOS_USDT_SPOT: SOSUSDT
SPARTA_USDT_SPOT: SPARTAUSDT
SPELL_USDT_SPOT: SPELLUSDT
SRM_USDT_SPOT: SRMUSDT
SSV_USDT_SPOT: SSVUSDT
STAT_USDT_SPOT: STATUSDT
STETH_USDT_SPOT: STETHUSDT
STG_USDT_SPOT: STGUSDT
STRM_USDT_SPOT: STRMUSDT
STX_USDT_SPOT: STXUSDT
SUIA_USDT_SPOT: SUIAUSDT
SUI_USDC_SPOT: SUIUSDC
SUI_USDT_SPOT: SUIUSDT
SUN_USDT_SPOT: SUNUSDT
SUSHI_USDT_SPOT: SUSHIUSDT
SWEAT_USDT_SPOT: SWEATUSDT
SYNR_USDT_SPOT: SYNRUSDT
TAMA_USDT_SPOT: TAMAUSDT
TAP_USDT_SPOT: TAPUSDT
TAVA_USDT_SPOT: TAVAUSDT
TEL_USDT_SPOT: TELUSDT
TENET_USDT_SPOT: TENETUSDT
THETA_USDT_SPOT: THETAUSDT
THN_USDT_SPOT: THNUSDT
TIA_USDT_SPOT: TIAUSDT
TIME_USDT_SPOT: TIMEUSDT
TOMI_USDT_SPOT: TOMIUSDT
TOMS_USDT_SPOT: TOMSUSDT
TON_USDT_SPOT: TONUSDT
TRIBE_USDT_SPOT: TRIBEUSDT
TRVL_USDT_SPOT: TRVLUSDT
TRX_USDC_SPOT: TRXUSDC
TRX_USDT_SPOT: TRXUSDT
TURBOS_USDT_SPOT: TURBOSUSDT
TWT_USDT_SPOT: TWTUSDT
T_USDT_SPOT: TUSDT
UMA_USDT_SPOT: UMAUSDT
UNI_USDT_SPOT: UNIUSDT
USDC_EUR_SPOT: USDCEUR
USDC_USDT_SPOT: USDCUSDT
USDD_USDT_SPOT: USDDUSDT
USDT_BRZ_SPOT: USDTBRZ
USDT_EUR_SPOT: USDTEUR
USTC_USDT_SPOT: USTCUSDT
VEGA_USDT_SPOT: VEGAUSDT
VELA_USDT_SPOT: VELAUSDT
VELO_USDT_SPOT: VELOUSDT
VEXT_USDT_SPOT: VEXTUSDT
VINU_USDT_SPOT: VINUUSDT
VPAD_USDT_SPOT: VPADUSDT
VRA_USDT_SPOT: VRAUSDT
VV_USDT_SPOT: VVUSDT
WAVES_USDT_SPOT: WAVESUSDT
WAXP_USDT_SPOT: WAXPUSDT
WBTC_BTC_SPOT: WBTCBTC
WBTC_USDT_SPOT: WBTCUSDT
WEMIX_USDT_SPOT: WEMIXUSDT
WLD_USDC_SPOT: WLDUSDC
WLD_USDT_SPOT: WLDUSDT
WLKN_USDT_SPOT: WLKNUSDT
WOO_USDT_SPOT: WOOUSDT
WWY_USDT_SPOT: WWYUSDT
XAVA_USDT_SPOT: XAVAUSDT
XCAD_USDT_SPOT: XCADUSDT
XDC_USDT_SPOT: XDCUSDT
XEC_USDT_SPOT: XECUSDT
XEM_USDT_SPOT: XEMUSDT
XETA_USDT_SPOT: XETAUSDT
XLM_BTC_SPOT: XLMBTC
XLM_USDC_SPOT: XLMUSDC
XLM_USDT_SPOT: XLMUSDT
XRP3L_USDT_SPOT: XRP3LUSDT
XRP3S_USDT_SPOT: XRP3SUSDT
XRP_BTC_SPOT: XRPBTC
XRP_EUR_SPOT: XRPEUR
XRP_USDC_SPOT: XRPUSDC
XRP_USDT_SPOT: XRPUSDT
XTZ_USDT_SPOT: XTZUSDT
XWG_USDT_SPOT: XWGUSDT
XYM_USDT_SPOT: XYMUSDT
YFI_USDT_SPOT: YFIUSDT
ZAM_USDT_SPOT: ZAMUSDT
ZEN_USDT_SPOT: ZENUSDT
ZIL_USDT_SPOT: ZILUSDT
ZRX_USDT_SPOT: ZRXUSDT
ZTX_USDT_SPOT: ZTXUSDT
