ADA_USD_IPERP: '0.0001'
BTCUSDH24: '0.50'
BTCUSDZ23: '0.50'
BTC_USD_IPERP: '0.50'
DOT_USD_IPERP: '0.005'
EOS_USD_IPERP: '0.001'
ETHUSDH24: '0.05'
ETHUSDZ23: '0.05'
ETH_USD_IPERP: '0.05'
LTC_USD_IPERP: '0.01'
MANA_USD_IPERP: '0.0005'
XRP_USD_IPERP: '0.0001'
