1INCH_USDT_SPOT: '0.0001'
1SOL_USDT_SPOT: '0.000001'
3P_USDT_SPOT: '0.000000000001'
AAVE_USDT_SPOT: '0.0001'
ACA_USDT_SPOT: '0.0001'
ACH_USDT_SPOT: '0.000001'
ACM_USDT_SPOT: '0.0001'
ACS_USDT_SPOT: '0.0000001'
ADA2L_USDT_SPOT: '0.0001'
ADA2S_USDT_SPOT: '0.0001'
ADA_EUR_SPOT: '0.0001'
ADA_USDC_SPOT: '0.0001'
ADA_USDT_SPOT: '0.0001'
AFC_USDT_SPOT: '0.0001'
AGIX_USDT_SPOT: '0.0001'
AGI_USDT_SPOT: '0.00001'
AGLA_USDT_SPOT: '0.00001'
AGLD_USDT_SPOT: '0.0001'
ALGO_BTC_SPOT: '0.00000001'
ALGO_USDT_SPOT: '0.00001'
ANKR_USDT_SPOT: '0.00001'
APE2L_USDT_SPOT: '0.0001'
APE2S_USDT_SPOT: '0.0001'
APEX_USDC_SPOT: '0.0001'
APEX_USDT_SPOT: '0.0001'
APE_USDC_SPOT: '0.0001'
APE_USDT_SPOT: '0.0001'
APT_USDC_SPOT: '0.0001'
APT_USDT_SPOT: '0.0001'
ARB_USDC_SPOT: '0.001'
ARB_USDT_SPOT: '0.001'
ARKM_USDT_SPOT: '0.00001'
AR_USDT_SPOT: '0.0001'
ATOM2L_USDT_SPOT: '0.0001'
ATOM2S_USDT_SPOT: '0.0001'
ATOM_USDT_SPOT: '0.0001'
AVAX2L_USDT_SPOT: '0.0001'
AVAX2S_USDT_SPOT: '0.0001'
AVAX_USDC_SPOT: '0.0001'
AVAX_USDT_SPOT: '0.0001'
AVA_USDT_SPOT: '0.0001'
AXL_USDT_SPOT: '0.0001'
AXS_USDT_SPOT: '0.0001'
AZY_USDT_SPOT: '0.00001'
BABYDOGE_USDT_SPOT: '0.000000000001'
BAR_USDT_SPOT: '0.0001'
BAT_USDT_SPOT: '0.0001'
BCH_USDT_SPOT: '0.1'
BEAM_USDT_SPOT: '0.000001'
BEL_USDT_SPOT: '0.0001'
BICO_USDT_SPOT: '0.0001'
BLUR_USDT_SPOT: '0.00001'
BNB_USDT_SPOT: '0.0001'
BNT_USDT_SPOT: '0.0001'
BOBA_USDT_SPOT: '0.00001'
BOB_USDT_SPOT: '0.00000001'
BONK_USDT_SPOT: '0.0000000001'
BTC3L_USDT_SPOT: '0.0001'
BTC3S_USDT_SPOT: '0.0001'
BTC_BRZ_SPOT: '0.1'
BTC_DAI_SPOT: '0.01'
BTC_EUR_SPOT: '0.01'
BTC_USDC_SPOT: '0.01'
BTC_USDT_SPOT: '0.01'
BTG_USDT_SPOT: '0.0001'
BTT_USDT_SPOT: '0.0000000001'
BUSD_USDT_SPOT: '0.0001'
C98_USDT_SPOT: '0.0001'
CAKE_USDT_SPOT: '0.0001'
CANDY_USDT_SPOT: '0.00001'
CAPO_USDT_SPOT: '0.000001'
CAPS_USDT_SPOT: '0.000001'
CAT_USDT_SPOT: '0.000001'
CBX_USDT_SPOT: '0.00001'
CELO_USDT_SPOT: '0.0001'
CEL_USDT_SPOT: '0.0001'
CGPT_USDT_SPOT: '0.000001'
CHRP_USDT_SPOT: '0.000001'
CHZ_USDC_SPOT: '0.0001'
CHZ_USDT_SPOT: '0.0001'
CITY_USDT_SPOT: '0.0001'
CMP_USDT_SPOT: '0.00001'
COMP_USDT_SPOT: '0.01'
CORE_USDT_SPOT: '0.0001'
COT_USDT_SPOT: '0.000001'
CO_USDT_SPOT: '0.000001'
CRV_USDT_SPOT: '0.0001'
CTC_USDT_SPOT: '0.000001'
CTT_USDT_SPOT: '0.000001'
CULT_USDT_SPOT: '0.000000001'
CUSD_USDT_SPOT: '0.0001'
CWAR_USDT_SPOT: '0.00001'
CYBER_USDT_SPOT: '0.0001'
DAI_USDT_SPOT: '0.0001'
DCR_USDT_SPOT: '0.0001'
DEFY_USDT_SPOT: '0.000001'
DEVT_USDT_SPOT: '0.0000001'
DFI_USDT_SPOT: '0.0001'
DGB_USDT_SPOT: '0.000001'
DICE_USDT_SPOT: '0.00001'
DLC_USDT_SPOT: '0.00001'
DOGE2L_USDT_SPOT: '0.0001'
DOGE2S_USDT_SPOT: '0.0001'
DOGE_EUR_SPOT: '0.00001'
DOGE_USDC_SPOT: '0.00001'
DOGE_USDT_SPOT: '0.00001'
DOME_USDT_SPOT: '0.000001'
DOT3L_USDT_SPOT: '0.0001'
DOT3S_USDT_SPOT: '0.0001'
DOT_BTC_SPOT: '0.00000001'
DOT_USDC_SPOT: '0.001'
DOT_USDT_SPOT: '0.001'
DPX_USDT_SPOT: '0.01'
DSRUN_USDT_SPOT: '0.00001'
DYDX_USDT_SPOT: '0.001'
DZOO_USDT_SPOT: '0.000001'
ECOX_USDT_SPOT: '0.0001'
EGLD_USDT_SPOT: '0.01'
EGO_USDT_SPOT: '0.00001'
ELDA_USDT_SPOT: '0.000001'
ELT_USDT_SPOT: '0.0000001'
ENJ_USDT_SPOT: '0.00001'
ENS_USDT_SPOT: '0.001'
EOS2L_USDT_SPOT: '0.0001'
EOS2S_USDT_SPOT: '0.0001'
EOS_USDC_SPOT: '0.0001'
EOS_USDT_SPOT: '0.0001'
ERTHA_USDT_SPOT: '0.000001'
ETC2L_USDT_SPOT: '0.0001'
ETC2S_USDT_SPOT: '0.0001'
ETC_USDT_SPOT: '0.01'
ETH3L_USDT_SPOT: '0.0001'
ETH3S_USDT_SPOT: '0.0001'
ETHW_USDT_SPOT: '0.0001'
ETH_BTC_SPOT: '0.000001'
ETH_DAI_SPOT: '0.01'
ETH_EUR_SPOT: '0.01'
ETH_USDC_SPOT: '0.01'
ETH_USDT_SPOT: '0.01'
EVER_USDT_SPOT: '0.00001'
FAME_USDT_SPOT: '0.000001'
FB_USDT_SPOT: '0.001'
FET_USDT_SPOT: '0.0001'
FIDA_USDT_SPOT: '0.0001'
FIL_USDC_SPOT: '0.001'
FIL_USDT_SPOT: '0.001'
FITFI_USDT_SPOT: '0.000001'
FLOKI_USDT_SPOT: '0.000000001'
FLOW_USDT_SPOT: '0.0001'
FLR_USDT_SPOT: '0.00001'
FMB_USDT_SPOT: '0.00001'
FON_USDT_SPOT: '0.0001'
FORT_USDT_SPOT: '0.0001'
FTM2L_USDT_SPOT: '0.0001'
FTM2S_USDT_SPOT: '0.0001'
FTM_USDT_SPOT: '0.00001'
FTT_USDT_SPOT: '0.0001'
FXS_USDT_SPOT: '0.0001'
GALA_USDT_SPOT: '0.00001'
GALFT_USDT_SPOT: '0.00001'
GAL_USDT_SPOT: '0.0001'
GCAKE_USDT_SPOT: '0.0000000001'
GENE_USDT_SPOT: '0.0001'
GGM_USDT_SPOT: '0.000001'
GLMR_USDT_SPOT: '0.0001'
GMT2L_USDT_SPOT: '0.000001'
GMT2S_USDT_SPOT: '0.0001'
GMT_USDC_SPOT: '0.0001'
GMT_USDT_SPOT: '0.0001'
GMX_USDT_SPOT: '0.0001'
GM_USDT_SPOT: '0.0000000001'
GNS_USDT_SPOT: '0.0001'
GODS_USDT_SPOT: '0.00001'
GPT_USDT_SPOT: '0.000001'
GRT_USDT_SPOT: '0.00001'
GSTS_USDT_SPOT: '0.000001'
GST_USDT_SPOT: '0.00001'
GSWIFT_USDT_SPOT: '0.00001'
HBAR_USDT_SPOT: '0.00001'
HERO_USDT_SPOT: '0.000001'
HFT_USDC_SPOT: '0.0001'
HFT_USDT_SPOT: '0.0001'
HNT_USDT_SPOT: '0.0001'
HOOK_USDT_SPOT: '0.0001'
HOT_USDT_SPOT: '0.000001'
HVH_USDT_SPOT: '0.00001'
ICP_USDC_SPOT: '0.0001'
ICP_USDT_SPOT: '0.0001'
ICX_USDT_SPOT: '0.00001'
ID_USDT_SPOT: '0.00001'
IMX_USDT_SPOT: '0.00001'
INJ_USDT_SPOT: '0.0001'
INTER_USDT_SPOT: '0.0001'
IZI_USDT_SPOT: '0.000001'
JASMY_USDT_SPOT: '0.000001'
JEFF_USDT_SPOT: '0.00001'
JST_USDT_SPOT: '0.00001'
JUV_USDT_SPOT: '0.0001'
KARATE_USDT_SPOT: '0.0000001'
KASTA_USDT_SPOT: '0.000001'
KAS_USDT_SPOT: '0.00001'
KAVA_USDT_SPOT: '0.0001'
KCAL_USDT_SPOT: '0.0001'
KDA_USDT_SPOT: '0.0001'
KLAY_USDT_SPOT: '0.00001'
KMON_USDT_SPOT: '0.000001'
KOK_USDT_SPOT: '0.00001'
KON_USDT_SPOT: '0.00001'
KRL_USDT_SPOT: '0.0001'
KSM_USDT_SPOT: '0.0001'
KUNCI_USDT_SPOT: '0.000001'
LADYS_USDT_SPOT: '0.00000000001'
LDO_USDC_SPOT: '0.0001'
LDO_USDT_SPOT: '0.0001'
LEVER_USDT_SPOT: '0.000001'
LFW_USDT_SPOT: '0.000001'
LGX_USDT_SPOT: '0.000001'
LING_USDT_SPOT: '0.000001'
LINK2L_USDT_SPOT: '0.0001'
LINK2S_USDT_SPOT: '0.0001'
LINK_USDC_SPOT: '0.0001'
LINK_USDT_SPOT: '0.0001'
LIS_USDT_SPOT: '0.000001'
LMWR_USDT_SPOT: '0.0001'
LOOKS_USDT_SPOT: '0.0001'
LRC_USDT_SPOT: '0.0001'
LTC2L_USDT_SPOT: '0.0001'
LTC2S_USDT_SPOT: '0.0001'
LTC_BTC_SPOT: '0.000001'
LTC_EUR_SPOT: '0.01'
LTC_USDC_SPOT: '0.01'
LTC_USDT_SPOT: '0.01'
LUNA_USDT_SPOT: '0.0001'
LUNC_USDC_SPOT: '0.00000001'
LUNC_USDT_SPOT: '0.00000001'
MAGIC_USDT_SPOT: '0.0001'
MANA_BTC_SPOT: '0.00000001'
MANA_USDC_SPOT: '0.0001'
MANA_USDT_SPOT: '0.0001'
MASK_USDT_SPOT: '0.0001'
MATIC2L_USDT_SPOT: '0.0001'
MATIC2S_USDT_SPOT: '0.0001'
MATIC_BTC_SPOT: '0.00000001'
MATIC_USDC_SPOT: '0.0001'
MATIC_USDT_SPOT: '0.0001'
MBS_USDT_SPOT: '0.000001'
MBX_USDT_SPOT: '0.001'
MCRT_USDT_SPOT: '0.000001'
MCT_USDT_SPOT: '0.00001'
MDAO_USDT_SPOT: '0.00001'
MEE_USDT_SPOT: '0.000001'
MELOS_USDT_SPOT: '0.000001'
MIBR_USDT_SPOT: '0.0001'
MINA_USDT_SPOT: '0.0001'
MIX_USDT_SPOT: '0.000001'
MKR_USDT_SPOT: '0.1'
MMC_USDT_SPOT: '0.000001'
MNT_BTC_SPOT: '0.00000001'
MNT_USDC_SPOT: '0.0001'
MNT_USDT_SPOT: '0.0001'
MNZ_USDT_SPOT: '0.0000001'
MOVEZ_USDT_SPOT: '0.000001'
MOVR_USDT_SPOT: '0.0001'
MPLX_USDT_SPOT: '0.00001'
MTC_USDT_SPOT: '0.00001'
MTK_USDT_SPOT: '0.000001'
MVL_USDT_SPOT: '0.000001'
MV_USDT_SPOT: '0.00001'
MX_USDT_SPOT: '0.0001'
NEAR_USDT_SPOT: '0.0001'
NEON_USDT_SPOT: '0.00001'
NESS_USDT_SPOT: '0.0001'
NEXO_USDT_SPOT: '0.0001'
NEXT_USDT_SPOT: '0.00001'
NFT_USDT_SPOT: '0.0000000001'
NYM_USDT_SPOT: '0.0001'
OAS_USDT_SPOT: '0.000001'
OBX_USDT_SPOT: '0.0000001'
OKG_USDT_SPOT: '0.000001'
OMG_USDT_SPOT: '0.001'
OMN_USDT_SPOT: '0.000001'
ONE_USDT_SPOT: '0.00001'
OP_USDC_SPOT: '0.0001'
OP_USDT_SPOT: '0.0001'
ORDI_USDT_SPOT: '0.0001'
ORT_USDT_SPOT: '0.000001'
PAXG_USDT_SPOT: '0.0001'
PENDLE_USDT_SPOT: '0.0001'
PEOPLE_USDT_SPOT: '0.00001'
PEPE2_USDT_SPOT: '0.000000000001'
PEPE_USDT_SPOT: '0.0000000001'
PERP_USDT_SPOT: '0.0001'
PIP_USDT_SPOT: '0.00001'
PLANET_USDT_SPOT: '0.00000001'
PLAY_USDT_SPOT: '0.00001'
PLT_USDT_SPOT: '0.00001'
PLY_USDT_SPOT: '0.0000001'
POKT_USDT_SPOT: '0.00001'
POL_USDT_SPOT: '0.0001'
PPT_USDT_SPOT: '0.0001'
PRIMAL_USDT_SPOT: '0.000001'
PRIME_USDT_SPOT: '0.001'
PSG_USDT_SPOT: '0.0001'
PSP_USDT_SPOT: '0.000001'
PSTAKE_USDT_SPOT: '0.00001'
PTU_USDT_SPOT: '0.0001'
PUMLX_USDT_SPOT: '0.00001'
PYUSD_USDT_SPOT: '0.0001'
QMALL_USDT_SPOT: '0.0001'
QNT_USDT_SPOT: '0.1'
QTUM_USDT_SPOT: '0.0001'
RACA_USDT_SPOT: '0.00000001'
RAIN_USDT_SPOT: '0.0000001'
RDNT_USDT_SPOT: '0.0001'
REAL_USDT_SPOT: '0.00001'
REN_USDT_SPOT: '0.00001'
RLTM_USDT_SPOT: '0.00001'
RNDR_USDT_SPOT: '0.0001'
ROND_USDT_SPOT: '0.000001'
ROSE_USDT_SPOT: '0.00001'
RPL_USDT_SPOT: '0.0001'
RSS3_USDT_SPOT: '0.00001'
RUNE_USDT_SPOT: '0.0001'
RVN_USDT_SPOT: '0.00001'
SAIL_USDT_SPOT: '0.00001'
SAITAMA_USDT_SPOT: '0.0000001'
SALD_USDT_SPOT: '0.00001'
SAND2L_USDT_SPOT: '0.0001'
SAND2S_USDT_SPOT: '0.0001'
SAND_BTC_SPOT: '0.00000001'
SAND_USDC_SPOT: '0.00001'
SAND_USDT_SPOT: '0.00001'
SCRT_USDT_SPOT: '0.0001'
SC_USDT_SPOT: '0.000001'
SD_USDT_SPOT: '0.0001'
SEILOR_USDT_SPOT: '0.000001'
SEI_USDT_SPOT: '0.0001'
SEOR_USDT_SPOT: '0.000001'
SFUND_USDT_SPOT: '0.00001'
SHIB_USDC_SPOT: '0.0000000001'
SHIB_USDT_SPOT: '0.0000000001'
SHILL_USDT_SPOT: '0.00001'
SIDUS_USDT_SPOT: '0.0000001'
SIS_USDT_SPOT: '0.00001'
SLG_USDC_SPOT: '0.000001'
SLG_USDT_SPOT: '0.000001'
SLP_USDT_SPOT: '0.000001'
SNX_USDT_SPOT: '0.0001'
SOLO_USDT_SPOT: '0.00001'
SOL_BTC_SPOT: '0.0000001'
SOL_EUR_SPOT: '0.01'
SOL_USDC_SPOT: '0.01'
SOL_USDT_SPOT: '0.01'
SON_USDT_SPOT: '0.0000001'
SOS_USDT_SPOT: '0.00000000001'
SPARTA_USDT_SPOT: '0.0001'
SPELL_USDT_SPOT: '0.00000001'
SRM_USDT_SPOT: '0.0001'
SSV_USDT_SPOT: '0.0001'
STAT_USDT_SPOT: '0.0001'
STETH_USDT_SPOT: '0.01'
STG_USDT_SPOT: '0.0001'
STRM_USDT_SPOT: '0.000001'
STX_USDT_SPOT: '0.00001'
SUIA_USDT_SPOT: '0.0001'
SUI_USDC_SPOT: '0.0001'
SUI_USDT_SPOT: '0.0001'
SUN_USDT_SPOT: '0.000001'
SUSHI_USDT_SPOT: '0.001'
SWEAT_USDT_SPOT: '0.000001'
SYNR_USDT_SPOT: '0.0000001'
TAMA_USDT_SPOT: '0.00001'
TAP_USDT_SPOT: '0.000001'
TAVA_USDT_SPOT: '0.00001'
TEL_USDT_SPOT: '0.000001'
TENET_USDT_SPOT: '0.00001'
THETA_USDT_SPOT: '0.0001'
THN_USDT_SPOT: '0.000001'
TIA_USDT_SPOT: '0.0001'
TIME_USDT_SPOT: '0.0001'
TOMI_USDT_SPOT: '0.001'
TOMS_USDT_SPOT: '0.000001'
TON_USDT_SPOT: '0.0001'
TRIBE_USDT_SPOT: '0.0001'
TRVL_USDT_SPOT: '0.000001'
TRX_USDC_SPOT: '0.00001'
TRX_USDT_SPOT: '0.00001'
TURBOS_USDT_SPOT: '0.000001'
TWT_USDT_SPOT: '0.0001'
T_USDT_SPOT: '0.00001'
UMA_USDT_SPOT: '0.0001'
UNI_USDT_SPOT: '0.0001'
USDC_EUR_SPOT: '0.0001'
USDC_USDT_SPOT: '0.0001'
USDD_USDT_SPOT: '0.0001'
USDT_BRZ_SPOT: '0.001'
USDT_EUR_SPOT: '0.0001'
USTC_USDT_SPOT: '0.00001'
VEGA_USDT_SPOT: '0.0001'
VELA_USDT_SPOT: '0.0001'
VELO_USDT_SPOT: '0.000001'
VEXT_USDT_SPOT: '0.00001'
VINU_USDT_SPOT: '0.00000000001'
VPAD_USDT_SPOT: '0.00001'
VRA_USDT_SPOT: '0.000001'
VV_USDT_SPOT: '0.000001'
WAVES_USDT_SPOT: '0.0001'
WAXP_USDT_SPOT: '0.00001'
WBTC_BTC_SPOT: '0.0001'
WBTC_USDT_SPOT: '0.01'
WEMIX_USDT_SPOT: '0.0001'
WLD_USDC_SPOT: '0.0001'
WLD_USDT_SPOT: '0.0001'
WLKN_USDT_SPOT: '0.000001'
WOO_USDT_SPOT: '0.00001'
WWY_USDT_SPOT: '0.000001'
XAVA_USDT_SPOT: '0.0001'
XCAD_USDT_SPOT: '0.0001'
XDC_USDT_SPOT: '0.00001'
XEC_USDT_SPOT: '0.00000001'
XEM_USDT_SPOT: '0.00001'
XETA_USDT_SPOT: '0.000001'
XLM_BTC_SPOT: '0.0000000001'
XLM_USDC_SPOT: '0.00001'
XLM_USDT_SPOT: '0.00001'
XRP3L_USDT_SPOT: '0.0001'
XRP3S_USDT_SPOT: '0.000001'
XRP_BTC_SPOT: '0.00000001'
XRP_EUR_SPOT: '0.0001'
XRP_USDC_SPOT: '0.0001'
XRP_USDT_SPOT: '0.0001'
XTZ_USDT_SPOT: '0.0001'
XWG_USDT_SPOT: '0.0000001'
XYM_USDT_SPOT: '0.00001'
YFI_USDT_SPOT: '0.01'
ZAM_USDT_SPOT: '0.000001'
ZEN_USDT_SPOT: '0.0001'
ZIL_USDT_SPOT: '0.00001'
ZRX_USDT_SPOT: '0.0001'
ZTX_USDT_SPOT: '0.00001'
