10000LADYS_USDT_PERP: '0.0000001'
10000NFT_USDT_PERP: '0.000001'
10000STARL_USDT_PERP: '0.00001'
1000BONK_USDT_PERP: '0.0000001'
1000BTT_USDT_PERP: '0.0000001'
1000FLOKI_USDT_PERP: '0.00001'
1000LUNC_USDT_PERP: '0.00001'
1000PEPE_USDT_PERP: '0.0000001'
1000XEC_USDT_PERP: '0.00001'
1INCH_USDT_PERP: '0.0005'
AAVE_USDT_PERP: '0.01'
ACH_USDT_PERP: '0.000001'
ADA_USDT_PERP: '0.0001'
AGIX_USDT_PERP: '0.00005'
AGLD_USDT_PERP: '0.0001'
AKRO_USDT_PERP: '0.000001'
ALGO_USDT_PERP: '0.0001'
ALICE_USDT_PERP: '0.001'
ALPACA_USDT_PERP: '0.00001'
ALPHA_USDT_PERP: '0.00005'
AMB_USDT_PERP: '0.000001'
ANKR_USDT_PERP: '0.00001'
ANT_USDT_PERP: '0.005'
APE_USDT_PERP: '0.0001'
API3_USDT_PERP: '0.001'
APT_USDT_PERP: '0.0005'
ARB_USDT_PERP: '0.0001'
ARKM_USDT_PERP: '0.00005'
ARK_USDT_PERP: '0.00001'
ARPA_USDT_PERP: '0.00001'
AR_USDT_PERP: '0.001'
ASTR_USDT_PERP: '0.000005'
ATA_USDT_PERP: '0.00005'
ATOM_USDT_PERP: '0.001'
AUCTION_USDT_PERP: '0.001'
AUDIO_USDT_PERP: '0.0001'
AVAX_USDT_PERP: '0.005'
AXS_USDT_PERP: '0.001'
BADGER_USDT_PERP: '0.0001'
BAKE_USDT_PERP: '0.0005'
BAL_USDT_PERP: '0.001'
BAND_USDT_PERP: '0.001'
BAT_USDT_PERP: '0.0005'
BCH_USDT_PERP: '0.05'
BEL_USDT_PERP: '0.0001'
BICO_USDT_PERP: '0.0001'
BIGTIME_USDT_PERP: '0.0001'
BLUR_USDT_PERP: '0.0001'
BLZ_USDT_PERP: '0.00001'
BNB_USDC_PERP: '0.05'
BNB_USDT_PERP: '0.05'
BNT_USDT_PERP: '0.00005'
BNX_USDT_PERP: '0.0005'
BOBA_USDT_PERP: '0.00005'
BOND_USDT_PERP: '0.001'
BSV_USDT_PERP: '0.01'
BSW_USDT_PERP: '0.00001'
BTC-03NOV23: '0.50'
BTC-10NOV23: '0.50'
BTC-17NOV23: '0.50'
BTC-24NOV23: '0.50'
BTC-28JUN24: '0.50'
BTC-29DEC23: '0.50'
BTC-29MAR24: '0.50'
BTC_USDC_PERP: '0.10'
BTC_USDT_PERP: '0.10'
BUSD_USDT_PERP: '0.0001'
C98_USDT_PERP: '0.0005'
CEEK_USDT_PERP: '0.00001'
CELO_USDT_PERP: '0.0001'
CELR_USDT_PERP: '0.00005'
CFX_USDT_PERP: '0.00001'
CHR_USDT_PERP: '0.0001'
CHZ_USDT_PERP: '0.00005'
CKB_USDT_PERP: '0.000005'
COMBO_USDT_PERP: '0.0005'
COMP_USDT_PERP: '0.05'
CORE_USDT_PERP: '0.0001'
COTI_USDT_PERP: '0.00001'
CRO_USDT_PERP: '0.00005'
CRV_USDT_PERP: '0.0001'
CTC_USDT_PERP: '0.00005'
CTK_USDT_PERP: '0.0001'
CTSI_USDT_PERP: '0.00005'
CVC_USDT_PERP: '0.00001'
CVX_USDT_PERP: '0.005'
CYBER_USDT_PERP: '0.0001'
DAR_USDT_PERP: '0.0005'
DASH_USDT_PERP: '0.05'
DENT_USDT_PERP: '0.000001'
DGB_USDT_PERP: '0.00001'
DODO_USDT_PERP: '0.00005'
DOGE_USDT_PERP: '0.00001'
DOT_USDT_PERP: '0.001'
DUSK_USDT_PERP: '0.00001'
DYDX_USDT_PERP: '0.001'
EDU_USDT_PERP: '0.0001'
EGLD_USDT_PERP: '0.05'
ENJ_USDT_PERP: '0.0005'
ENS_USDT_PERP: '0.001'
EOS_USDT_PERP: '0.0001'
ETC_USDC_PERP: '0.005'
ETC_USDT_PERP: '0.005'
ETH-03NOV23: '0.05'
ETH-10NOV23: '0.05'
ETH-17NOV23: '0.05'
ETH-24NOV23: '0.05'
ETH-28JUN24: '0.05'
ETH-29DEC23: '0.05'
ETH-29MAR24: '0.05'
ETHW_USDT_PERP: '0.001'
ETH_USDC_PERP: '0.01'
ETH_USDT_PERP: '0.01'
FET_USDT_PERP: '0.00005'
FIL_USDT_PERP: '0.001'
FITFI_USDT_PERP: '0.000001'
FLM_USDT_PERP: '0.00005'
FLOW_USDT_PERP: '0.0005'
FLR_USDT_PERP: '0.00001'
FORTH_USDT_PERP: '0.0001'
FRONT_USDT_PERP: '0.00001'
FTM_USDT_PERP: '0.0001'
FXS_USDT_PERP: '0.0005'
GALA_USDT_PERP: '0.00001'
GAL_USDT_PERP: '0.0005'
GAS_USDT_PERP: '0.001'
GFT_USDT_PERP: '0.00001'
GLMR_USDT_PERP: '0.00005'
GLM_USDT_PERP: '0.00001'
GMT_USDT_PERP: '0.0001'
GMX_USDT_PERP: '0.005'
GPT_USDT_PERP: '0.000001'
GRT_USDT_PERP: '0.00001'
GTC_USDT_PERP: '0.001'
HBAR_USDT_PERP: '0.00001'
HFT_USDT_PERP: '0.0001'
HIFI_USDT_PERP: '0.00001'
HIGH_USDT_PERP: '0.0005'
HNT_USDT_PERP: '0.001'
HOOK_USDT_PERP: '0.0005'
HOT_USDT_PERP: '0.000001'
ICP_USDT_PERP: '0.001'
ICX_USDT_PERP: '0.0001'
IDEX_USDT_PERP: '0.00001'
ID_USDT_PERP: '0.00005'
ILV_USDT_PERP: '0.005'
IMX_USDT_PERP: '0.0001'
INJ_USDT_PERP: '0.0005'
IOST_USDT_PERP: '0.000001'
IOTA_USDT_PERP: '0.0005'
IOTX_USDT_PERP: '0.00005'
JASMY_USDT_PERP: '0.000001'
JOE_USDT_PERP: '0.00005'
JST_USDT_PERP: '0.00001'
KAS_USDT_PERP: '0.00001'
KAVA_USDT_PERP: '0.0001'
KDA_USDT_PERP: '0.0001'
KEY_USDT_PERP: '0.0000005'
KLAY_USDT_PERP: '0.0005'
KNC_USDT_PERP: '0.0001'
KSM_USDT_PERP: '0.05'
LDO_USDT_PERP: '0.0005'
LEVER_USDT_PERP: '0.000001'
LINA_USDT_PERP: '0.00001'
LINK_USDT_PERP: '0.001'
LIT_USDT_PERP: '0.0001'
LOOKS_USDT_PERP: '0.00005'
LOOM_USDT_PERP: '0.000001'
LPT_USDT_PERP: '0.001'
LQTY_USDT_PERP: '0.0005'
LRC_USDT_PERP: '0.0001'
LTC_USDT_PERP: '0.01'
LUNA2_USDT_PERP: '0.0001'
MAGIC_USDT_PERP: '0.0001'
MANA_USDT_PERP: '0.0001'
MASK_USDT_PERP: '0.001'
MATIC_USDC_PERP: '0.0001'
MATIC_USDT_PERP: '0.0001'
MAV_USDT_PERP: '0.0001'
MC_USDT_PERP: '0.00001'
MDT_USDT_PERP: '0.000005'
MINA_USDT_PERP: '0.0001'
MKR_USDT_PERP: '0.5'
MNT_USDT_PERP: '0.00001'
MTL_USDT_PERP: '0.0001'
MULTI_USDT_PERP: '0.0001'
NEAR_USDT_PERP: '0.001'
NEO_USDT_PERP: '0.001'
NKN_USDT_PERP: '0.00001'
NMR_USDT_PERP: '0.001'
NTRN_USDT_PERP: '0.0001'
OCEAN_USDT_PERP: '0.0001'
OGN_USDT_PERP: '0.0001'
OG_USDT_PERP: '0.0001'
OMG_USDT_PERP: '0.0001'
ONE_USDT_PERP: '0.00001'
ONT_USDT_PERP: '0.00005'
OP_USDC_PERP: '0.0005'
OP_USDT_PERP: '0.0001'
ORBS_USDT_PERP: '0.00001'
ORDI_USDT_PERP: '0.001'
OXT_USDT_PERP: '0.00001'
PAXG_USDT_PERP: '1'
PENDLE_USDT_PERP: '0.0001'
PEOPLE_USDT_PERP: '0.00005'
PERP_USDT_PERP: '0.00001'
PHB_USDT_PERP: '0.0001'
POLYX_USDT_PERP: '0.0001'
POWR_USDT_PERP: '0.0001'
PROM_USDT_PERP: '0.0001'
QNT_USDT_PERP: '0.01'
QTUM_USDT_PERP: '0.005'
RAD_USDT_PERP: '0.001'
RDNT_USDT_PERP: '0.00005'
REEF_USDT_PERP: '0.000001'
REN_USDT_PERP: '0.00001'
REQ_USDT_PERP: '0.00001'
RIF_USDT_PERP: '0.0001'
RLC_USDT_PERP: '0.0005'
RNDR_USDT_PERP: '0.00005'
ROSE_USDT_PERP: '0.00001'
RPL_USDT_PERP: '0.005'
RSR_USDT_PERP: '0.000001'
RSS3_USDT_PERP: '0.00005'
RUNE_USDT_PERP: '0.001'
RVN_USDT_PERP: '0.00005'
SAND_USDT_PERP: '0.0001'
SCRT_USDT_PERP: '0.0001'
SC_USDT_PERP: '0.000001'
SEI_USDT_PERP: '0.00001'
SFP_USDT_PERP: '0.0001'
SHIB1000_USDT_PERP: '0.000001'
SKL_USDT_PERP: '0.00001'
SLP_USDT_PERP: '0.000001'
SNX_USDT_PERP: '0.001'
SOL_USDC_PERP: '0.005'
SOL_USDT_PERP: '0.001'
SPELL_USDT_PERP: '0.0000001'
SSV_USDT_PERP: '0.005'
STEEM_USDT_PERP: '0.0001'
STG_USDT_PERP: '0.0001'
STMX_USDT_PERP: '0.000005'
STORJ_USDT_PERP: '0.0005'
STPT_USDT_PERP: '0.00001'
STRAX_USDT_PERP: '0.001'
STX_USDT_PERP: '0.00005'
SUI_USDT_PERP: '0.00001'
SUN_USDT_PERP: '0.000005'
SUSHI_USDT_PERP: '0.0001'
SWEAT_USDT_PERP: '0.000001'
SXP_USDT_PERP: '0.0005'
THETA_USDT_PERP: '0.0001'
TIA_USDT_PERP: '0.0001'
TLM_USDT_PERP: '0.000005'
TOMI_USDT_PERP: '0.001'
TOMO_USDT_PERP: '0.0005'
TON_USDT_PERP: '0.0001'
TRB_USDT_PERP: '0.001'
TRU_USDT_PERP: '0.00005'
TRX_USDT_PERP: '0.00001'
TWT_USDT_PERP: '0.0005'
T_USDT_PERP: '0.00001'
UMA_USDT_PERP: '0.001'
UNFI_USDT_PERP: '0.0005'
UNI_USDT_PERP: '0.001'
USDC_USDT_PERP: '0.0001'
VET_USDT_PERP: '0.00005'
VGX_USDT_PERP: '0.00001'
VRA_USDT_PERP: '0.000001'
WAVES_USDT_PERP: '0.0005'
WAXP_USDT_PERP: '0.0001'
WLD_USDT_PERP: '0.001'
WOO_USDT_PERP: '0.0001'
WSM_USDT_PERP: '0.00001'
XCN_USDT_PERP: '0.0000001'
XEM_USDT_PERP: '0.00001'
XLM_USDT_PERP: '0.00005'
XMR_USDT_PERP: '0.05'
XNO_USDT_PERP: '0.0001'
XRP_USDC_PERP: '0.0001'
XRP_USDT_PERP: '0.0001'
XTZ_USDT_PERP: '0.0001'
XVG_USDT_PERP: '0.0000005'
XVS_USDT_PERP: '0.0001'
YFII_USDT_PERP: '0.05'
YFI_USDT_PERP: '5'
YGG_USDT_PERP: '0.0001'
ZEC_USDT_PERP: '0.05'
ZEN_USDT_PERP: '0.001'
ZIL_USDT_PERP: '0.00001'
ZRX_USDT_PERP: '0.0001'
