ALIASES = {
    'proj': 'project',
    'config': 'configuration',
    'const': 'constant',
    'dir': 'directory',
    'env': 'environment',
    'fh': 'file_handler',
    'fh_name': 'file_handler_name',
    'fh_kwargs': 'file_handler_keyword_arguments',
    'fh_lv': 'file_handler_level',
    'sh': 'stream_handler',
    'sh_lv': 'stream_handler_level',
    'th': 'telegram_handler',
    'th_kwargs': 'telegram_handler_keyword_arguments',
    'th_lv': 'telegram_handler_level',
    'lv': 'level',
    'rec': 'record',
    'rec_fmt': 'log_record_format',
    'ts': 'timestamp',
    'ts_fmt': 'log_timestamp_format',
    'fmt': 'format',

    'multi': 'multiplier',
    'tfee': 'taker_fee',
    'mfee': 'maker_fee',
    'bps': 'basis_points',
    'lsize': 'lot_size',
    'tsize': 'tick_size',
    
    'bkr': 'broker',
    'exch': 'exchange',
    'strat': 'strategy',
    'pdt': 'product',
    'epdt': 'external_product',
    'bccy': 'base_currency',
    'qccy': 'quote_currency',
    'ccy': 'currency',
    'eccy': 'external_currency',
    'px': 'price',
    'qty': 'quantity',
    'ptype': 'product_type',
    'eptype': 'external_product_type',
    'otype': 'order_type',
    'acc': 'account',
    'mdl': 'model',
    'ftr': 'feature',

    'o': 'order',
    'ltp': 'last_traded_price',
    'ltq': 'last_traded_quantity',
    'lts': 'last_traded_size',
    'ltt': 'last_traded_time',

    'SPOT': 'cryptocurrency',
    'PERP': 'perpetual_contract',  # linear perpetual
    'IPERP': 'inverse_perpetual_contract',
    'FUT': 'futures_contract',  # linear futures
    'IFUT': 'inverse_futures_contract',
    'OPT': 'options_contract',  # linear options
    'STK': 'stock',
    'CMDTY': 'commodity',
    'FX': 'forex',
    'MTF': 'mutual_fund',
    'ETF': 'exchange_traded_fund',
    'CW': 'current_week',
    'NW': 'next_week',
    'CM': 'current_month',
    'NM': 'next_month',
    'CQ': 'current_quarter',
    'NQ': 'next_quarter',

    'ret': 'return',
    'res': 'result',
    'resp': 'response',
    'req': 'request',

    'prev': 'previous',
    'thd': 'thread',
    'cb': 'callback',
    'om': 'order_manager',

    'ack': 'acknowledge',
    'acked': 'acknowledged',
    'auth': 'authentication',
    'authed': 'authenticated',

    'ws': 'websocket',
    'rest': 'rest_api',

    'sub': 'subscribe',
    'ttl': 'total',
    'freq': 'frequency',
    'num': 'number',
    'tf': 'timeframe',
    'mod': 'model',
    'agg': 'aggregate',
    'resol': 'resolution',

    'IB': 'interactive brokers',

    'bg': 'background',
    'boa': 'bid_or_ask',

    'tv': 'trading_venue',
}
