[workspace]
authors = ["softwareentrepreneer <softwareentrepreneer+pfund@gmail.com>"]
channels = ["conda-forge"]
name = "pfund"
# macos = min version of macOS required by torch>=2.12.0
platforms = [{ platform = "osx-arm64", macos = "14.0" }, "linux-aarch64", "linux-64", "win-64"]
# NOTE: should match with setup-pixi in ci.yml
requires-pixi = ">=0.81.0,<0.82.0"
# FIXME: set it back to "14 days" when the package is stable
exclude-newer = "0d"

[pypi-exclude-newer]
afterpython = "0d"
pfeed = "0d"
pfund-kit = "0d"
pfund-plot = "0d"
mtflow = "0d"

[tasks]

[tasks.test-all]
depends-on = [
  { task = "test", environment = "py312" },
  { task = "test", environment = "py313" },
  { task = "test", environment = "py314" },
  # { task = "test", environment = "py315" },
]

[environments]
default = ["py312", "dev", "test", "optional"]
py312 = ["py312", "test", "optional"]
py313 = ["py313", "test", "optional"]
py314 = ["py314", "test", "optional"]
# py315 = ["py315", "test", "optional"]

[dependencies]

# TEMP
[pypi-options]
prerelease-mode = "allow"

[pypi-dependencies]
pfund-kit = ">=0.1.21"
pfeed = ">=0.0.20"
apscheduler = ">=3.11.3"
httpx2 = { version = ">=2.13.1", extras = ["http2"] }
websockets = ">=16.1.0"
numba = ">=0.68.0"

[feature.optional.pypi-dependencies]
pfund-plot = {version = ">=0.0.5", extras = ["marimo"]}
# TODO: enable when ready
# mtflow = ">=0.0.1.dev2"
ray = { version = ">=2.59.0", extras = ["default"] }
ta-lib = ">=0.8.1"
joblib = ">=1.6.0"
scikit-learn = ">=1.9.1"
torch = ">=2.14.1"
safetensors = ">=0.8.0"
# Trading Venues:
# pfund-hyperliquid = ">=0.0.1"
# pfund-alpaca = ">=0.0.1.dev1"
# pfund-bybit = ">=0.0.1.dev1"
# pfund-binance = ">=0.0.1.dev1"
# pfund-okx = ">=0.0.1.dev1"

[feature.dev.pypi-dependencies]
pfund = { path = ".", editable = true }
# TEMP
pfeed = { path = "../pfeed", editable = true }
pfund-plot = { path = "../pfund-plot", editable = true, extras = ["marimo"] }
pfund-kit = { path = "../pfund-kit", editable = true }
mtflow = { path = "../mtflow", editable = true }
afterpython = ">=0.4.0"
memray = ">=1.19.3"

[feature.dev.dependencies]
graphviz = ">=14.1.2"
python-graphviz = ">=0.21"

[feature.test.pypi-dependencies]
pfund = { path = ".", editable = true }
pytest = ">=9.1.1"
pytest-cov = ">=7.1.0"
pytest-mock = ">=3.16.0"
pytest-xdist = ">=3.8.0"
pytest-asyncio = ">=1.4.0"
pytest-recording = ">=0.14.0"
pytest-markdown-docs = ">=0.9.2"
# testcontainers = ">=4.14.2"
[feature.test.tasks]
test = "pytest"
test-new = "pytest --record-mode=all"  # record new interactions, useful to update recordings in case data formats returned have changed
test-ci = "pytest --record-mode=none"  # fail a test if no recording is found

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

# [feature.py315.dependencies]
# python = "3.15.*"
