[workspace]
authors = ["softwareentrepreneer <softwareentrepreneer+pfund@gmail.com>"]
channels = ["conda-forge"]
name = "pfund"
platforms = ["osx-arm64", "linux-64"]
# NOTE: this depends on the lock version used in setup-pixi in ci.yml
# currently the max lock-version supported is 6
requires-pixi = "<=0.67.2"  # command: pixi workspace requires-pixi set "<=0.67.2"

[tasks]

[tasks.test-all]
depends-on = [
  { task = "test", environment = "py311" },
  { task = "test", environment = "py312" },
  { task = "test", environment = "py313" },
]

[environments]
compare = ["py313", "dev", "optional", "compare"]
default = ["py311", "dev", "optional"]
py311 = ["py311", "test", "optional"]
py312 = ["py312", "test", "optional"]
py313 = ["py313", "test", "optional"]

[dependencies]

[pypi-dependencies]
pfund-kit = ">=0.1.11"
pfeed = ">=0.0.16"
apscheduler = ">=3.11.3"
httpx2 = { version = ">=2.5.0", extras = ["http2"] }
websockets = ">=16.0.0"
numba = ">=0.66.0"

[feature.optional.system-requirements]
macos = "14.0"  # min version of macOS required by torch>=2.12.0

[feature.optional.pypi-dependencies]
pfeed = { version = ">=0.0.16", extras = ["yfinance"] }
pfolio = ">=0.0.4"
pfund-plot = {version = ">=0.0.5", extras = ["marimo"]}
# TODO: enable when ready
# mtflow = ">=0.0.1.dev2"
pfund-ibapi = "==10.47.1"
alpaca-py = ">=0.43.5"
hyperliquid-python-sdk = ">=0.24.0"
joblib = ">=1.5.3"
scikit-learn = ">=1.9.0"
torch = ">=2.12.1"
safetensors = ">=0.8.0"
jax = ">=0.10.2"
ta-lib = ">=0.7.0"

[feature.dev.pypi-dependencies]
pfund = { path = ".", editable = true }
# TEMP
pfeed = { path = "../pfeed", editable = true, extras = ["yfinance"] }
pfund-plot = { path = "../pfund-plot", editable = true, extras = ["marimo"] }
pfund-kit = { path = "../pfund-kit", editable = true }
pfolio = { path = "../pfolio", editable = true }
mtflow = { path = "../mtflow", editable = true }
afterpython = ">=0.3.16"
basedpyright = ">=1.39.9"
jupytext = ">=1.19.3"
jupyterlab = ">=4.5.7"
memray = ">=1.19.3"
pandas-stubs = ">=3.0.3.260530"
pybit = ">=5.16.0"
lightning = ">=2.6.5"
flax = ">=0.12.7"
equinox = ">=0.13.8"
optax = ">=0.2.8"

[feature.dev.dependencies]
graphviz = ">=14.1.2"
python-graphviz = ">=0.21"

[feature.compare.pypi-dependencies]
vectorbt = ">=1.0.0"
backtrader = ">=1.9.78.123"
backtesting = ">=0.6.5"
nautilus-trader = ">=1.230.0"
lib-pybroker = ">=1.2.12"

[feature.test.pypi-dependencies]
pfund = { path = ".", editable = true }
pytest = ">=9.1.1"
pytest-cov = ">=7.1.0"
pytest-mock = ">=3.15.1"
pytest-xdist = ">=3.8.0"
pytest-asyncio = ">=1.4.0"
pytest-recording = ">=0.13.4"
# testcontainers = ">=4.14.2"
[feature.test.tasks]
test = "pytest"
test-new = "pytest --record-mode=all"  # record new interactions, useful to update recordings in case data formats returned have changed
test-ci = "pytest --record-mode=none"  # fail a test if no recording is found

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"
