[company]
name = "PFund.ai"
url = "https://pfund.ai"

[website]
url = "https://pfund.pfund.ai"
favicon = "favicon.svg"
logo = "logo.svg"
logo_dark = "logo.svg"
thumbnail = "thumbnail.png"
announcement = ""
readme_py = "wasm"
api_reference = false
