from typing import ClassVar

from pydantic import Field, model_validator

from pfund.typing import Currency, ProductName
from pfund.enums import TradingVenue
from pfund.engines.settings.base_engine_settings import BaseEngineSettings


'''
settings: BacktestEngineSettings = {
        'commit_to_git': False,
        'retention_period': '7d',
    }
'''
class BacktestEngineSettings(BaseEngineSettings):
    # If not provided, will use the default initial balances in SimulatedBroker
    initial_balances: ClassVar[dict[TradingVenue, dict[Currency, float]] | None] = None
    initial_positions: ClassVar[dict[TradingVenue, dict[ProductName, float]] | None] = None
    retention_period: int = Field(default=7, ge=1)
    commit_to_git: bool = Field(default=False)
    save_backtests: bool = Field(default=True)
    # if True, reuses signals from dumped signal_df in _next() instead of recalculating the signals. 
    # This will make event-driven backtesting a LOT faster but inconsistent with live trading.
    reuse_signals: bool = Field(default=False)
    # if True, asserts signals generated by event-driven backtesting and vectorized backtesting are the same,
    # by collecting results during event-driven backtesting.
    assert_signals: bool = Field(default=True)

    @model_validator(mode="after")
    def check_assert_signals(self):
        if self.reuse_signals and self.assert_signals:
            raise ValueError('reuse_signals must be False when assert_signals=True in event-driven backtesting')
        return self