# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "/ PFund's Documentation"
author: Stephen Yau
logo: images/logo-dark.svg
copyright: '2024, PFund.ai | Powered by "Awesome Sphinx Theme" | '

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/PFund-Software-Ltd/pfund  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # google_analytics_id: {GA_TRACKING_ID_PLACEHOLDER}
  home_page_in_navbar: true
  favicon: images/favicon.ico
  # NOTE: buttons will not work when using sphinxawesome_theme
  # use_issues_button: true
  # use_repository_button: true
  # use_edit_page_button: true

sphinx:
  config:
    nb_render_text_lexer: "none"
    html_theme: sphinxawesome_theme
    html_context:
      default_mode: light
    # NOTE: dark_theme.css is only used when using sphinxawesome_theme
    # it is generated by "pygmentize -S <your_theme> -f html -a .dark > dark_theme.css"
    html_css_files: ["custom.css", "dark_theme.css"]
    # NOTE: some of the keys inside `html_theme_options` will not work when using sphinxawesome_theme unless they are specified in the sphinxawesome.xyz documentation
    html_theme_options:
      # pygment_light_style: "friendly"
      # pygment_dark_style: "lightbulb"
      show_prev_next: true
      main_nav_links:
        "PFund Hub": "https://pfund.ai/hub"
        "pfeed": "https://github.com/PFund-Software-Ltd/pfeed"
      extra_header_link_icons:
        GitHub:
          icon: >-
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0112 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z"/>
            </svg>
          link: "https://github.com/PFund-Software-Ltd/pfund"
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'