# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "/ PFund's Documentation"
author: Stephen Yau
logo: images/logo-dark.svg
copyright: '2024, PFund.ai | Powered by "Awesome Sphinx Theme" | '

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/PFund-Software-Ltd/pfund  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  google_analytics_id: {GA_TRACKING_ID_PLACEHOLDER}
  home_page_in_navbar: true
  favicon: images/favicon.ico
  # NOTE: buttons will not work when using sphinxawesome_theme
  # use_issues_button: true
  # use_repository_button: true
  # use_edit_page_button: true

sphinx:
  config:
    nb_render_text_lexer: "none"
    html_theme: sphinxawesome_theme
    html_context:
      default_mode: dark
    # NOTE: dark_theme.css is only used when using sphinxawesome_theme
    # it is generated by "pygmentize -S <your_theme> -f html -a .dark > dark_theme.css"
    html_css_files: ["custom.css", "dark_theme.css"]
    # NOTE: `html_theme_options` will not work when using sphinxawesome_theme
    # html_theme_options:
    #   pygment_light_style: "friendly"
    #   pygment_dark_style: "lightbulb"
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinxawesome_theme.highlighting'