#!/bin/bash

source ../.env

# Extract the Google Analytics ID from the environment
GA_ID=$(echo $GA_TRACKING_ID)

# Check OS type and adjust sed command accordingly
if [[ "$OSTYPE" == "darwin"* ]]; then
    SED_CMD="sed -i ''"
else
    SED_CMD="sed -i"
fi

# Backup the original _config.yml
cp _config.yml _config_backup.yml

# Replace the placeholder in the YAML file with the actual Google Analytics ID
$SED_CMD "s/{GA_TRACKING_ID_PLACEHOLDER}/$GA_ID/" _config.yml

# Build
jupyter-book build docs/ --all

# Restore the original _config.yml from backup
mv _config_backup.yml _config.yml

# Remove the backup file generated by sed on macOS
rm _config.yml\'\'